### ISSUE TITLE
Add export image to .raw filetype

### ISSUE THREAD

**Issue by MadDog443** [chunky-dev/chunky#1009]
While .pfm is a raw file of sorts it's not very useful or versatile for many things and is only supported by 2 photo editing applications. It would honestly be better to also allow us to export to .raw because it is one of if not the most commonly used raw file type in the photography industry meaning more software supports it.

**Comment by ShirleyNekoDev** [comment]
To quote https://en.wikipedia.org/wiki/Raw_image_format#Standardization
> Providing a detailed and concise description of the content of raw files is highly problematic. There is no single raw format; formats can be similar or radically different. Different manufacturers use their own proprietary and typically undocumented formats, which are collectively known as raw format.

If you could provide which specific raw format you'd like to see implemented and/or have a specification for it, an implementation can be build pretty fast. 🙂
As an alternative I'd suggest using `.tiff` or `.exr` via https://github.com/ShirleyNekoDev/Chunky-MagickExportPlugin .

**Comment by leMaik** [comment]
I'm with @ShirleyNekoDev on this one. There is not "the" raw format and the stuff that cameras output isn't well suited for CGI. We already have tiff and pfm, adding exr to chunky would be cool. But compared to pfm, it's a more complex format
