### ISSUE TITLE
1.12.2 Incorrect stairs, glass and doors + missing flowers

### ISSUE THREAD

**Issue by TheRealJayjayli** [chunky-dev/chunky#1028]
List of known bugs:

- [x] Some shulker boxes
- [x] Top stone slabs
- [ ] minecraft:double_plant half:upper, all variants
- [ ] stairs (1.12 worlds)
- [ ] glass (1.12)
- [ ] fences (1.12)
- [ ] iron bars (1.12)
- [ ] half doors (1.12)

---
Original issue:

**From the 1.12.2 debug world, the following flowers are missing:**
```
minecraft:double_plant
facing: east / west / south / north
half: upper
variant: paeonia / double_rose / double_fern / double_grass / syringa / sunflower
```

------------------------------------------------------
**It also appears corner stairs are incorrect:**
```
[Any stair variant]
facing: east / west / south / north
half: top / bottom
shape: inner_left / inner_right / outer_left / outer_right
```
Instead of appearing normally, corner stairs are shown as regular straight stairs.

------------------------------------------------------
**Glass also always appears as a single pane when there are no other panes surrounding it, such as this:**

![image](https://user-images.githubusercontent.com/52780721/129491872-7cf0e43c-ae8b-4a22-8a0f-8af47217344c.png)

This effect also applies to fences and iron bars.

------------------------------------------------------

**Half doors are also always `facing=north, half=upper, hinge=right, open=false` regardless of direction/half:**

![image](https://user-images.githubusercontent.com/52780721/129492045-863057d9-6056-4be8-a7c4-7aabe9e4d431.png)

**Comment by leMaik** [comment]
Pre-flattening support is a pain. 😅 Before [some version], bars, fence and glass panes only depended on adjacent blocks. Seems like they got data at some point.

**Comment by jackjt8** [comment]
Other issues - 

Lava + Water heights are incorrect:

![image](https://user-images.githubusercontent.com/3740917/136107181-18c1ab9c-0205-4312-9e2d-e6a86196ff39.png)

![image](https://user-images.githubusercontent.com/3740917/136107202-31138cdd-e08d-4092-a514-45c4c32d255a.png)

![image](https://user-images.githubusercontent.com/3740917/136107228-517d3c63-b796-4141-be04-d4026f617ae5.png)

![image](https://user-images.githubusercontent.com/3740917/136107247-c7c853af-9a27-4b39-abd3-a73b11161efc.png)

---

No clue what blocks there are. Can't interact with them.

![image](https://user-images.githubusercontent.com/3740917/136107470-32130b56-f602-4fef-96f0-56b3743885f2.png)


![image](https://user-images.githubusercontent.com/3740917/136107449-6fcc2458-d735-473a-89b0-9d949c56209d.png)

---

Locked Repeaters, Melon Seeds, Pumpkin Stems

![image](https://user-images.githubusercontent.com/3740917/136107748-1e3fc1c8-c9c8-4aa0-b378-e5b2591721f8.png)

![image](https://user-images.githubusercontent.com/3740917/136107794-e63ee042-ccd7-4bff-8ed7-d3ec3a2fbc03.png)

---

oak_fences

![image](https://user-images.githubusercontent.com/3740917/136108069-0f33205e-d6cc-475d-9f81-8c211eee59da.png)

![image](https://user-images.githubusercontent.com/3740917/136108049-48b4fb93-1352-4b53-ba5e-d65127ea1f36.png)

---

iron_bar

![image](https://user-images.githubusercontent.com/3740917/136108152-0106f54b-9579-48ca-b89f-6d6272580f6c.png)

![image](https://user-images.githubusercontent.com/3740917/136108175-db9e7078-54b0-41f2-a04b-f3670b745a9f.png)

---

brewing_stand

![image](https://user-images.githubusercontent.com/3740917/136108277-a943ccad-f6f7-4fed-b3bf-d2979c95dad7.png)

![image](https://user-images.githubusercontent.com/3740917/136108287-7748b9ab-9b57-4c3c-888a-ad74b2da6077.png)

---

nether_brick_fence

![image](https://user-images.githubusercontent.com/3740917/136108447-56defddb-dcce-4618-b865-4fc1f0475d7e.png)

![image](https://user-images.githubusercontent.com/3740917/136108426-7acff2d5-3a7e-4103-8971-1428d31b738f.png)


---

cobblestone_wall & mossy_cobblestone_wall

![image](https://user-images.githubusercontent.com/3740917/136108698-f8660f76-d900-4112-8f2c-f61a325dde7a.png)

![image](https://user-images.githubusercontent.com/3740917/136108722-43790e51-372f-41a9-8f16-f23d266bddb1.png)

---

chorus_plant

![image](https://user-images.githubusercontent.com/3740917/136108933-26f11ae5-3c05-4389-b877-124f76ec26d8.png)

![image](https://user-images.githubusercontent.com/3740917/136108900-3b4940da-488f-4600-9971-006c5157a161.png)

**Comment by leMaik** [comment]
It seems like the pre-flattening debug world renders all block states but doesn't store them. There's no way we can support that. If you find missing or different block states in _actual_ worlds or in 1.13+ debug worlds, please open new issues.

That said, some blocks were fixed thanks to this issue. :+1:
