### ISSUE TITLE
Doesn't correct open world generated with purpur

### ISSUE THREAD

**Issue by PerchunPak** [chunky-dev/chunky#1054]
[Purpur](https://purpur.pl3x.net) is a server core
And Chunky think that every biom is an ocean, also printing in console 2 warnings
![image](https://user-images.githubusercontent.com/68118654/136280676-6326850d-7b17-460d-9b2f-f760a6af6c7e.png)

**Comment by NotStirred** [comment]
cannot reproduce with the world you sent

**Comment by NotStirred** [comment]
You can ignore this error if purpur is trimming region files without validating the header
chunky is just spitting out warnings
