### ISSUE TITLE
cannot load textures correctly while loading 1.14.4 blocks even if apply 1.14.4 jar

### ISSUE THREAD

**Issue by Twinkling-G** [chunky-dev/chunky#1060]
Chunk2.0 seems to cannot load textures correctly while loading 1.14.4 save even if apply 1.14.4 jar or 1.14.4 resourcepack ,for example,there are 4 blocks missing their textures ,and they are barrel,stonecutter,iron_trapdoor and diorite_wall.
![Snipaste_2021-10-17_09-13-50](https://user-images.githubusercontent.com/92655873/137606443-c02e7108-4172-43bf-965a-76dc2f9a802a.jpg)
![Snipaste_2021-10-17_09-14-35](https://user-images.githubusercontent.com/92655873/137606444-094823c0-6392-4a9f-8f27-a4632f75d243.jpg)

**Comment by NotStirred** [comment]
Which chunky version are you using exactly?
