### ISSUE TITLE
Launcher fail to find JavaFx should point to new documentation.

### ISSUE THREAD

**Issue by ThatRedox** [chunky-dev/chunky#1068]
![unknown-12](https://user-images.githubusercontent.com/42661490/140599410-7a78eb7b-9d92-4310-bdc4-dd78c56e627b.png)
Currently points to Jack's guide. Should now point to new documentation.

**Comment by jackjt8** [comment]
Note - Redirects from jackjt8's Guide to Chunky to the new docs should now function correctly without 404'ing. This was a misconfiguration issue.

We also need to edit the About links within Chunky.
![image](https://user-images.githubusercontent.com/3740917/140607337-ff89a381-d839-4164-9c63-8be47c7ee08a.png)

Online Documentation --> https://chunky-dev.github.io/docs/

~~Chunky 2.1 Documentation~~

We could also remove my guide as it's currently a shell of it's former self now. Still not sure where/how the final topics will integrate but we can figure that out.

**Comment by leMaik** [comment]
#1058 will also fix the links

**Comment by jackjt8** [comment]
> ![unknown-12](https://user-images.githubusercontent.com/42661490/140599410-7a78eb7b-9d92-4310-bdc4-dd78c56e627b.png) Currently points to Jack's guide. Should now point to new documentation.

It seems that someone has already updated the Launcher link to one of leMaik's redirect URLs ("https://chunky.lemaik.de/java11") so I will skip this step for now.

> We also need to edit the About links within Chunky. ...

Given #1058 is slated to be a `2.5` only UI change I will fix the links in `2.4.x` separately.

**Comment by jackjt8** [comment]
@leMaik Issue was resolved.
