### ISSUE TITLE
Sky light visible through the water plane in chunks where the void is visible.

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1072]
There is a world in which many chunks have no terrain, and are empty down to the void. Load some chunks, and enable the water plane. Light can't pass through blocks but it can pass through the water plane. Since there are no blocks beneath the water plane, and since the Preetham sky simulates below the horizon, when the selection is viewed from above you can notice a difference in water color. The Nishita sky doesn't simulate below the horizon and the water color is consistent. Please see attached comparision images.

The area through which the sky shines is dependent on the selection size. If the measurements of the selection do not exceed 16 chunks on either axis, then the size of the area is 16 by 16 chunks. If the selection exceeds 16 chunks on one or more axes, then the area quadruples to 32 by 32 chunks. If the selection exceeds 32 chunks on either axis, then the area quadruples again, to 64 by 64 chunks. The pattern probably continues as the selection size increases.
![default_2021-11-19_13-28-33-5](https://user-images.githubusercontent.com/92183530/142626751-448654a7-7123-4c27-b925-96433c19d6e8.png)
![default_2021-11-19_13-28-33-12](https://user-images.githubusercontent.com/92183530/142626762-cfd8f0bc-bc8f-4089-8be7-00653e71a636.png)

**Comment by Peregrine05** [comment]
Closing in favor of #1642

**Comment by leMaik** [comment]
Whhops, I guess I should have searched through the existing issues first.
