### ISSUE TITLE
Support for OpenEXR output

### ISSUE THREAD

**Issue by ImSyphia** [chunky-dev/chunky#1084]
Adding support for 32 bit floating-point OpenEXR output would be helpful since outputting as TIFF and PNG restrict the dynamic range, as well as have post-processing applied, and PFM has quite limited support by external programs.

**Comment by jackjt8** [comment]
Already supported via [Magick Export Plugin](https://github.com/ShirleyNekoDev/Chunky-MagickExportPlugin) via the [Plugin List on the docs](https://chunky-dev.github.io/docs/plugins/plugins/).

**Comment by ImSyphia** [comment]
I wasn't aware of that plugin, thanks!
