### ISSUE TITLE
Installed version 1.4.5 and it is "blocking" me from using 2.4.1

### ISSUE THREAD

**Issue by aboothered** [chunky-dev/chunky#1088]
I had the intention of accessing a 1.16 world, but didnt know about the limitations of the old version, which I installed due to being an exe and it is easier to manage as Im really not used to jars and these "complex" things. When I found out (by noticing it wasnt working), uninstalled the undesired version and replaced it with the new ChunkyLauncher.jar. 
As soon as I entered the command on the prompt, though, it went straight into 1.4.5 again, and doesnt matter what I do, it keeps happening.
It is most probably just me being dumb when it comes to how files work, but still Im not sure on how to fix it...
Any help is highly appreciated!

**Comment by ThisIsBrady** [comment]
Did you make sure to hit "Check for updates" in the launcher after you got the new one?

**Comment by aboothered** [comment]
> Did you make sure to hit "Check for updates" in the launcher after you got the new one?

To get the launcher again I had to reinstall 1.4.5, and upon clicking on said button, it was unable to find any...

**Comment by ThisIsBrady** [comment]
In the bottom left corner of the launcher, what version number is it?

**Comment by aboothered** [comment]
It says 1.10.1

**Comment by ThisIsBrady** [comment]
Ah, that's an old version. The current version of the launcher is 1.12.2. You can get it from Step 3 on [this page](https://chunky-dev.github.io/docs/getting_started/#universal-jar-chunky-launcher-setup). Once you download it, hit 'Check for updates' then it should find and download the latest version.

**Comment by aboothered** [comment]
Alright, thank you! o/
