### ISSUE TITLE
Renaming and saving a scene does not create new directory

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1093]
2.3.0, 2.4.0, 2.4.1 - Works
2.5.0-11-g7b67ad1d - Fails...

Expected behaviour - In previous versions: Creating a scene with `scenename_a` and saving produces a directory within `scenes` called `scenename_a` with scene files as `scenename_a.<something>`. Upon renaming the scene with say `scenename_b` and saving a new directory called `scenename_b` and all scene files created during a save action are created in the new directory with the new files names. Chunky can open these scenes.

What's going wrong - In Chunky 2.5.0-11-g7b67ad1d, and maybe previous development versions, The act of renaming a scene and saving it does not create a new directory for `scenename_b`. Instead all files for `scenename_b` are stored within the directory for  `scenename_a`. This breaks loading of these new scenes.

**Comment by leMaik** [comment]
Bisected this, it's a regression from #1075

**Comment by jackjt8** [comment]
Issue is not fixed in 2.5.0-15-g1b1a5d5b, 2.5.0-51-gad88ccd7, **2.5.0-59-g57ea7363 (latest as of 28/02/2022)**.

Altering the name of `scene_a` to `scene_b` still places `scene_b` files in the directory for `scene_a`.

**Comment by leMaik** [comment]
Huh... Either a new regression or not fixed correctly before.

**Comment by jackjt8** [comment]
I should also add-

If a fresh scene is made, sometimes it'll write `scene_a` to `scenes` and not `scenes/scene_a`. I'm not sure what the trigger of this is. Other times it writes files correctly. 
![image](https://user-images.githubusercontent.com/3740917/156248289-5d1d483c-ea14-4b0e-b1cd-ac1be2e896fe.png)

**Comment by jackjt8** [comment]
Small update -

Headless mode is able to read files in `/scenes/` but not `/scenes/scene_name`
