### ISSUE TITLE
Save, Save As, Save a Copy As...

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1094]
Current behaviour when naming and saving a scene is inconsistent and confusing.

Changing the scene name does not simply rename the scene but it creates a duplicate of the scene; Keeping a scene with both the old name and then the new name.

Options in other software may help us here:

![image](https://user-images.githubusercontent.com/3740917/145834327-fab99670-ce98-42ef-8dda-2548b29234a0.png)

- [x] Save - Save current scene.
- [x] Save As - Save the current scene but with a new name (do not duplicate) - ie rename the scene.
- [x] Save a Copy As - Save current scene as a copy with a new name. 

Making these changes would mean that the current way to rename a scene may need to be removed or retooled with a prompt to ask the user if they want to rename or to duplicate the scene with a new name.

Some of these options are in Pull #1058 but not all of them.
---

Related - https://github.com/chunky-dev/chunky/issues/1093, https://github.com/chunky-dev/chunky/pull/1058

**Comment by leMaik** [comment]
What you describe is not the default behavior of "Save as" and "Save copy as". The difference is only whether the copy is immediately opened or not. 

I'll implement both in #1058

**Comment by jackjt8** [comment]
> What you describe is not the default behavior of "Save as" and "Save copy as". The difference is only whether the copy is immediately opened or not.
> 
> I'll implement both in #1058

The exact wording of these options could certainly be different and more standardized. Wasn't sure on the default behaviour.

**Comment by leMaik** [comment]
@jackjt8 Neither was I, I had to look it up in different applications :sweat_smile:

So here's how #1058 now implements it:
* Save saves (overwrites)
* Save as saves with a new name (and immediately opens that copy)
* Save a copy saves with a new name but keeps the original opened

The wording is from Libre Office, but I'm pretty sure it's the same in many other apps (just can't find a lot of examples)

**Comment by jackjt8** [comment]
That's perfect
