### ISSUE TITLE
Y max clip hidden - No indication within UI design

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1096]
Currently `Y max clip` is hidden within the `Scenes` tab.

Multiple new users struggle to find this option as there is no visual indication that further options exist.

![image](https://user-images.githubusercontent.com/3740917/146061832-a07af253-96c6-4d6a-baf9-0bc0c9a94daa.png)

---

Ideally, we need to show a secondary scrollbar within any Tab that is too long to display fully or to provide some other form of indication such as an Arrow?

Example:

![image](https://user-images.githubusercontent.com/3740917/146062253-4be54ef2-61aa-459b-bab6-0822b2e7451d.png)

**Comment by leMaik** [comment]
There was some branch where someone fixed this iirc. Last time i looked into this, i didn't find the issue.

**Comment by leMaik** [comment]
This will be fixed in 2.4.2 and 2.5.0
