### ISSUE TITLE
Scene Y clip does not auto populate like Map Y level

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1097]
`Map View` tabs `Min/Max Y level` fields are autopopulated depending on the world version/height.

The `Scene` tabs `Y min/max clip` are not autopopulated and use default values (0,256) instead. To avoid confusion these should be autopopulated similar to how `Min/Max Y level` are.

**Comment by leMaik** [comment]
This was fixed by #1168 and is also fixed in Chunky 2.4.2, right?

**Comment by jackjt8** [comment]
Correct
