### ISSUE TITLE
Warn User on Java 32 Bit Use

### ISSUE THREAD

**Issue by Huskydog9988** [chunky-dev/chunky#1100]
The base concept is really simple, the user should be told that they are using a 32 bit version of Java. As to how this could be done I have a few ideas. 
* Print a message to the console, the obvious draw back though is it that the user would have to enable the console
* Have a banner/alert in the launcher that does the same thing as the console message, but in the launcher.
* Limit the ram to 4G

**Comment by jackjt8** [comment]
Maximum memory allocation for 32 bit Java depends on multiple factors.

"For a 32-bit process model, the maximum virtual address size of the process is typically 4 GB, though some operating systems limit this to 2 GB or 3 GB. The maximum heap size is typically -Xmx3800m (1600m) for 2 GB limits), though the actual limitation is application dependent."
