### ISSUE TITLE
In 1.18 WorldPainter worlds, blocks above the old build limit don't load

### ISSUE THREAD

**Issue by MattQ012** [chunky-dev/chunky#1111]
In a 1.18 any blocks that are above y=256 do not load when starting a scene

**Comment by NotStirred** [comment]
What version of chunky are you using?

Is this world a world painter world? Can you send one of the region files of the world so I can test it?

**Comment by MattQ012** [comment]
The version is 2.5.0-19-g6d153f00 and it is a worldpainter world

**Comment by NotStirred** [comment]
This is a known bug with worldpainter worlds, I assume you found the `y max clip` to change that setting?
