### ISSUE TITLE
Foliage and grass colors should depend on altitude

### ISSUE THREAD

**Issue by leMaik** [chunky-dev/chunky#1156]
According to the [Minecraft Wiki](https://minecraft.fandom.com/wiki/Tint#Other), the temperature used for tinting blocks depends on the altitude. Currently, Chunky always uses the temperature at sea level.

> A biome's rainfall value is typically a value from 0.0 to 1.0, and its temperature starts at a given value at sea level (e.g. 2.0 for Desert or −0.5 for Snowy Taiga) and decreases by 0.00166667 [1/600] for each meter above sea level.

**Comment by ThatRedox** [comment]
Looking into the source code, neither the grass nor foliage colors depend on the altitude. They both only use the base temperature and rainfall values.
![image](https://user-images.githubusercontent.com/42661490/152477310-53250cf0-965c-47a0-87a9-8036c3841f0e.png)
![image](https://user-images.githubusercontent.com/42661490/152477487-e227df8d-8cb8-47a6-8d00-93ad4ecf4078.png)
