### ISSUE TITLE
The entity list in the Entities tab is not auto-filled when a new scene with entities is created.

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1165]
To reproduce:
1. Open the Entites tab.
2. Select chunks with players in the map view.
3. Open the Scene tab.
4. Make sure Load entities: Players is selected.
5. Load selected chunks.

The entities list will remain empty, despite there being players in the scene. To see the entities in the list, close the Entities tab, and then open it again.

**Comment by NotStirred** [comment]
This is not specific to the entities tab, though the entities tab is the only place it's obviously happening

The entire gui doesn't update when `SynchronousSceneManager#loadChunks` or `SynchronousSceneManager#reloadChunks` are called
