### ISSUE TITLE
Add a way to browse for a scene to load

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1173]
Currently, Chunky allows you to change the world directory and browse for a world to load from within the _Change World_ menu. The _Load Scene_ menu does not have such functionality. The _Change Scene Directory_ option exists, but it is hidden in the rarely accessed _Options_ tab. _Change Scene Directory_ should be added to the _Load Scene_ menu, and "Browse for another scene" should be added as an option to that menu as well, to mirror the _Change World_ menu. It would also be useful in the event someone downloads a scene to render, but does not know that is should go in the `scenes` folder. Then they can simply browse for the scene.

**Comment by leMaik** [comment]
Related to #1058
