### ISSUE TITLE
Add a way to set the release channel in headless mode

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1182]
Currently, the launcher has --update, but there are no flags for downloading a different version or setting the release channel to download from.

**Comment by Peregrine05** [comment]
This would be useful for those who wish to render 1.18 worlds headlessly.

**Comment by Peregrine05** [comment]
This has been fixed at some point.

**Comment by leMaik** [comment]
How can one specify the release channel in headless mode?

**Comment by Peregrine05** [comment]
Use the commands: 
`java -jar ChunkyLauncher.jar --update "stable-snapshot"`
`java -jar ChunkyLauncher.jar --update "snapshot"`
`java -jar ChunkyLauncher.jar --update "stable"`

**Comment by Peregrine05** [comment]
I don't know about the PR release channels.

**Comment by leMaik** [comment]
Didn't remember that this was added
