### ISSUE TITLE
Multiple empty chunks on the renders

### ISSUE THREAD

**Issue by Lemonzyy** [chunky-dev/chunky#1191]
Multiple chunk-sized holes are visible on the renders. Probably because those chunks are only made up of stone. This is surely an optimization of Chunky but these empty chunks are still visible on the rendering which of course is unintended.
![Example](https://user-images.githubusercontent.com/47032639/157743526-1f799f49-b2ca-4cfc-b71a-f548722c5962.png)

Here is the Minecraft region with the bug (1.18.1):
[r.0.0.zip](https://github.com/chunky-dev/chunky/files/8226819/r.0.0.zip)
Here is the camera position and orientation:
![Camera position+orientation](https://user-images.githubusercontent.com/47032639/157744189-7af956fd-f181-455f-b7cd-181136a39746.png)

**Comment by leMaik** [comment]
This has been broken since we added 1.18 support. :/ https://github.com/chunky-dev/chunky/pull/1078
