### ISSUE TITLE
Opening the `Advanced` tab causes a render reset.

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1199]
What could be causing this? Opening that tab should not change any settings to cause Chunky to reset the render. If the render has progressed far enough, the reset can be cancelled.

**Comment by leMaik** [comment]
I can't reproduce this in the latest snapshot. What version does this appear in?

**Comment by ThatRedox** [comment]
This appears to happen since `AdvancedTab.update` does not deregister listeners when setting the scene options. `Scene.setPreventNormalEmitterWithSampling`, `.setRenderer`, and `.setPreviewRenderer` do not check if the new value is equal to the old value before forcing a scene refresh.

**Comment by Peregrine05** [comment]
I believe it only happens when you open the Advanced tab for the first time. If it had already been opened, then I don't think it will affect the render.
