### ISSUE TITLE
New autocomplete of `.0` makes entering numbers much harder

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1202]
Re: https://github.com/chunky-dev/chunky/issues/1202#issue-1171530509

Version: 2.5.0-SNAPSHOT.75.g8bd28790

The new field autocomplete automatically adds `.0` to numbers... Which in theory is a good idea... In practice.. it's not.

Current behaviour:

Lets try to enter `25.8`. Typing this as you would in previous versions gives you `2.05.8` which is invalid. Remove everything except for the `2` and trying again.. `25.0.8`. Which also is not valid.

Expected behaviour:

When typing, the `.0` should only show up after you have finished and press enter.

**Comment by ShirleyNekoDev** [comment]
Expected behaviour sounds good 👍 

I will fix this using a spinner number input instead of a filtered/converting text input.
Best solution for UI is composition instead of inheritance (most of the time) ^^
