### ISSUE TITLE
The SPP counter is inaccurate

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1213]
Currently, for example, it states `Rendering 1 of 100`. That is inaccurate because while it states "Rendering 1 of 100", it is actually rendering 2 of 100. Therefore, to be accurate, it should either state, instead of "Rendering 1 of 100", `Rendered 1 of 100`, OR `Rendering 2 of 100`.

**Comment by leMaik** [comment]
Probably not the most urgent issue but I'll keep it open... :roll_eyes:
