### ISSUE TITLE
Emitter light cuts off in water

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1231]
Emitters that are underwater do not light the area above the water as brightly as underneath the water. But maybe this is supposed to happen.

Closed by #1514.
![Emitter2-above-water-146](https://user-images.githubusercontent.com/92183530/163693694-95e49b31-328a-4dc0-9719-30c922216aa5.png)

Emitters that are outside the water do not illuminate the blocks under the water as brightly as above the water, even when water opacity is set to 0, and water specular is set to 0, but maybe that is simply a result of the water material. Also, lighting cutoffs and periodic waves of brighter lighting that intersect with the surface of the water at the corners of blocks similar to what appear in #1230 are seen; however, the lighting below the cutoff that is below the surface of the water is darker, instead of lighter than the lighting above that cutoff.
![Emitter-above-water-580](https://user-images.githubusercontent.com/92183530/163693820-4e5d56ba-8fec-4013-8375-1faaa60b8886.png)
![Emitter-underwater-non-integer-65](https://user-images.githubusercontent.com/92183530/163693827-90aea52b-bc86-4280-869c-30df63d769fe.png)

When the camera is at certain locations underneath the water, the lighting cuts off in strange ways.
![Emitter-underwater-integer-65](https://user-images.githubusercontent.com/92183530/163693846-d747885d-5de7-4fc8-ab8e-1ff79dd30470.png)

Here is the scene with the settings that produced the strange lighting cutoffs.
[Emitters test.zip](https://github.com/chunky-dev/chunky/files/8500758/Emitters.test.zip)

**Comment by jackjt8** [comment]
Possibly related to #637
