### ISSUE TITLE
Chunky does not support transparency in skins.

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1254]
As shown below, Minecraft and the Minecraft launcher support displaying transpareny in the outer layer of Minecraft skins. My skin contains transparent pixels in its second layer.
![image](https://user-images.githubusercontent.com/92183530/167175707-1a03dc88-e5e3-42cc-8eff-3046cbbbd49d.png)

Chunky, however, does not. It displays pixels with transparency as completely opaque.
![image](https://user-images.githubusercontent.com/92183530/167175834-e2cfaf98-dbfb-42b4-80ba-53e2904b1648.png)

**Comment by leMaik** [comment]
Something to do about how your skin handles transparency. Can you give me your skin png file?

**Comment by Peregrine05** [comment]
![Peregrine05](https://user-images.githubusercontent.com/92183530/167206164-0cc09be3-5135-428b-aea1-dd3df0c3dbfb.png)
Here is my skin.

**Comment by Peregrine05** [comment]
Chunky displays transparency in skins in the final render. The preview does not display transparency.

![image](https://user-images.githubusercontent.com/92183530/175517944-d7a54482-ccab-426c-8d04-59a28f1b542f.png)
