### ISSUE TITLE
chunky does not detect worlds that are not directly on the root of the world directory

### ISSUE THREAD

**Issue by megamasterbloc** [chunky-dev/chunky#1272]
When a world is no directly in the world directory but rather in a folder within that directory chunky will not find the world unless the world dir is specifically changed to the parent folder.

**Comment by leMaik** [comment]
Minecraft doesn't do this either. We'll add a button to browse for a specific world directory instead.

**Comment by leMaik** [comment]
We already have a _Browse for another world_ button.
