### ISSUE TITLE
Water world mode no longer works in the latest snapshot

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1281]
Prior to Snapshot 115.gbe340072, water world worked as expected. In the latest snapshot, water world mode no longer works. Instead, the grid pattern at the bottom of the world simply takes on a slight tint.

Water world disabled in preview:
![image](https://user-images.githubusercontent.com/92183530/170744343-48982902-5319-4008-a270-d0ad0652e303.png)

Water world enabled in preview:
![image](https://user-images.githubusercontent.com/92183530/170744377-cb1adffd-c233-4dc5-9cf8-d8bc108ca8b3.png)

Water world enabled in render:
![image](https://user-images.githubusercontent.com/92183530/170744430-9ab1d17e-7308-4d94-8669-ee0bfef44aea.png)

(The world is Greenfield 0.5.3.)

**Comment by leMaik** [comment]
I can't reproduce this anymore.

**Comment by leMaik** [comment]
Only happens if the BiomeStructure implementation is TRIVIAL_3D or TRIVIAL_2d
