### ISSUE TITLE
Water world mode does not accept negative values for water height.

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1291]
1.18 worlds allow negative values for blocks, so the water world mode should also allow this. As a side note, clouds already allow negative values for their Y-value.

**Comment by NotStirred** [comment]
The slider is bound to `0`-`256` but you can still enter values beyond those bounds.
There have been a lot of questions around this though, is there anything that can be done to make this more obvious?

**Comment by Peregrine05** [comment]
Ah, I see what the problem was. The water plane does not appear below the Y-min clip of the scene, which was set to a higher value than 0.

**Comment by Peregrine05** [comment]
Something such as this can be used.
![image](https://user-images.githubusercontent.com/92183530/172639877-bbf45202-f60b-4028-8227-24920ee0adbf.png)
