### ISSUE TITLE
Sky mode settings do not indicate their saved values when a saved scene is loaded.

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1296]
When a saved scene is loaded, the Sky mode settings that were saved do not change to indicate their saved values. Instead, they display the default values, even though the render preview displays the result of the saved values.

**Comment by leMaik** [comment]
I can't reproduce this.

**Comment by Peregrine05** [comment]
In my case, this happened with `Skymap (panoramic)`. To reproduce, follow the instructions below.
Step 1: Load a chunk.
Step 2: Set the `Sky mode` to `Skymap (panoramic)`.
Step 3: Load a skymap.
Step 4: Set the `Vertical resolution` to `Full`.
Step 5: Change the `Skymap rotation` to a value besides *0*.
Step 6: Save the scene.
Step 7: Close Chunky.
Step 8: Launch Chunky.
Step 9: Load the saved scene.
The `Sky mode settings` Will display the settings at their defaults, those being `Vertical resolution: Half (mirrored)`, and `Skymap rotation: 0`.
