### ISSUE TITLE
Chunky crashing when trying to start it on macOS with java18 and 17

### ISSUE THREAD

**Issue by TomerGamerTV** [chunky-dev/chunky#1297]
I got this error after clicking the launch button 
```
java --module-path ~/.chunky/javafx/lib --add-modules javafx.controls,javafx.fxml -jar ChunkyLauncher.jar
Unchecked exception caused Chunky to close.
java.lang.NoClassDefFoundError: javafx/application/Application
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at se.llbit.chunky.main.Chunky.main(Chunky.java:224)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 10 more```

**Comment by Peregrine05** [comment]
This means that you need to add JavaFX to the Java Options in the Chunky Launcher. Paste the following string of text into the `Java options` input field in the Chunky Launcher before any other text that may already be there, and add a space before that other text.

`--module-path ~/.chunky/javafx/lib --add-modules javafx.controls,javafx.fxml`

The Java Options input field is accessed by opening the Advanced menu. After the text has been pasted in, click Launch.

**Comment by TomerGamerTV** [comment]
> --module-path ~/.chunky/javafx/lib --add-modules javafx.controls,javafx.fxml

`Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.controls not found`

**Comment by TomerGamerTV** [comment]
okay idk how but i was able to fix it by removing the text you gave me from the launch option and putting it normally in the program
Before:
`java --module-path ~/.chunky/javafx/lib --add-modules javafx.controls,javafx.fxml -jar ChunkyLauncher.jar`
After:
`java --module-path ~/.chunky/javafx/lib -jar ChunkyLauncher.jar`

I will close it if everything works

**Comment by Peregrine05** [comment]
Are you getting the errors that you described above when you are trying to start the Chunky Launcher, or when you are clicking the `Launch` button?

**Comment by TomerGamerTV** [comment]
> Are you getting the errors that you described above when you are trying to start the Chunky Launcher, or when you are clicking the `Launch` button in the Chunky Launcher?

i was getting the error after clicking launch in the launcher

**Comment by Peregrine05** [comment]
Unfortunately, I do not have access to a Mac to be able to test the solution which usually works on Windows and Linux machines. Typically, adding the same JavaFX arguments (`--module-path "<path/to/javafx/lib>" --add-modules javafx.controls,javafx.fxml`) that were used to start the Chunky Launcher to the `Java options` input field in the Chunky Launcher is what must be done to actually launch Chunky.

**Comment by TomerGamerTV** [comment]
I was able to fix the problem, I removed this `--add-modules javafx.controls,javafx.fxml` text from the argument inside the terminal to the launcher java option and now everything works, I'm able to render images fine

**Comment by TomerGamerTV** [comment]
bruh and now i cant run it on windows because it says that this --add-modules thing is missing

```
Unrecognized option: --module-path
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by Peregrine05** [comment]
This means that you are running Chunky with Java 8, which does not support that argument. Furthermore, the Chunky launcher can not download Chunky updates when run using Java 8, so you need to run it with Java 17. The wasiest way to do this is to uninstall Java 8 and then install Java 17 and JavaFX according to the instructions found [here](https://chunky-dev.github.io/docs/getting_started/). Note that if you decide to install JavaFX to `C:\Users\<username>\.chunky`, the folder name is "javafx", not "openjfx".

**Comment by Peregrine05** [comment]
Closing due to lack of response. Comment on the issue again if you still need assistance.
