### ISSUE TITLE
Sun luminosity description

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1303]
re:#1215

`Sun luminosity` - "Absolute brightness of the sun. Used when fast sun sampling is disabled."

Given we don't have a toggle for fast sun sampling anymore the second line here doesn't make much sense.

**Comment by Peregrine05** [comment]
Well, the dropdown menu is essentially a toggle. you toggle between the different SSS modes.

**Comment by leMaik** [comment]
_Only used for …_?
