### ISSUE TITLE
Search for updates instead of telling the user to do so if there are no chunky versions installed

### ISSUE THREAD

**Issue by leMaik** [chunky-dev/chunky#1304]
This should improve the out-of-box-experience.

**Comment by Peregrine05** [comment]
https://github.com/chunky-dev/chunky/issues/1457#issuecomment-1800420664

This is already done automatically when the launcher is opened.

**Comment by leMaik** [comment]
There actually is a condition where the launcher would complain about no version being installed and not search for updates. I did try to fix this but didn't commit it, I'll create a draft PR.
