### ISSUE TITLE
Removed my entire map (PLEASE HELP)

### ISSUE THREAD

**Issue by kdk088** [chunky-dev/chunky#1314]
Hi, I had a stupid massive issue and I just beg to all gods of this miserable univers to get a solution:

After finishing a Minecraft map I had been working for a month,  which was made for comission, I went to Chunky to get a good render image and show it to my customers. After picking the chunks to render, I wanted to re-adjust them and went to the "Chunks" page in order to clear the selection, but I stupidly pressed "Delete selection" instead of "Clear selection" and my entire map got fully removed. Now there's only an empty air map and I find no way to restore it.

I know I should have made backups, but never expected chunky to be so dangerous in these terms.  I honestly didn't even know Chunky could modify my in-game maps. I just wish there's a way to get those files back or I am fucked. Please, I need your help!

**Comment by leMaik** [comment]
This behavior is only in old versions of Chunky and I'm afraid we can't help you with this. :cry: 

We have, however, already fixed this issue in newer versions of Chunky, and make it **very** clear that this would delete chunks:
![image](https://user-images.githubusercontent.com/5544859/174492261-ec51988c-11bc-481a-bf5c-c0469a9dad4a.png)

**Comment by Peregrine05** [comment]
Unfortunately, if you are using the 2.4.2 release, then the `Delete selected chunks` and the `Clear selection` buttons have the same icon, so it can be easy to mix them up.
Chunky should have prompted you to delete the chunks after the `Delete selected chunks` button was pressed with a dialog box.
![image](https://user-images.githubusercontent.com/92183530/174491880-45af1ce8-a0a6-4e79-8091-4b21fe1188f0.png)

If you somehow managed to confirm the deletion of the chunks, then there is probably no way to restore those chunks. You might be able to find a previous version of the map in the `Previous versions` tab of the world folder properties window.

**Comment by NotStirred** [comment]
it is actually technically possible to recover the chunks due to the way that chunky deletes them, though they would not be in the same position they were originally

**Comment by kdk088** [comment]
> it is actually technically possible to recover the chunks due to the way that chunky deletes them, though they would not be in the same position they were originally

I am all ears

**Comment by NotStirred** [comment]
it's also entirely possible that many (or all) chunks could be missed and lost forever. what you'll likely get out is all of the chunks in very weird positions, which you'd then need to copy with worldedit and move then around

I'd recommend you to not open it in minecraft if you haven't already, or if you have close it as quickly as you can

If you send one of the region files from the world I can attempt to write a tool to extract the chunks

**Comment by kdk088** [comment]
> it's also entirely possible that many (or all) chunks could be missed and lost forever. what you'll likely get out is all of the chunks in very weird positions, which you'd then need to copy with worldedit and move then around
> 
> I'd recommend you to not open it in minecraft if you haven't already, or if you have close it as quickly as you can
> 
> If you send one of the region files from the world I can attempt to write a tool to extract the chunks

Whatever you need. Any help is a lot. What do you need exactly and how do I send you?

**Comment by NotStirred** [comment]
if you don't mind sharing the entire world you can just zip it and upload it to google drive

I just need the `region` folder, and `level.dat` file though

**Comment by kdk088** [comment]
I'll upload the entire world in google drive with no problems. Just leave me en e-mail so I can share it specifically with you, please

**Comment by NotStirred** [comment]
of course, my github email is tom.martin1239@gmail.com

**Comment by kdk088** [comment]
I'll send it to you immediately. I opened the world when the issue happened, but I didn't stay for more than 1 minute inside. I wish it's not such an issue :(

**Comment by NotStirred** [comment]
we can only hope that minecraft didn't clear the region files :crossed_fingers:

**Comment by NotStirred** [comment]
sadly I think minecraft has removed the vast majority of the chunks, pretty much the entire area from `-3000, 1500` to `512, 512`. There are a few regions with some data in them, I'll see if I can do anything with those

**Comment by kdk088** [comment]
Thank you, even though the bad news. I'll expect more updates from you :(

**Comment by NotStirred** [comment]
To give an update here, sadly there was only a few chunks remaining in the region files, (roughly 5x5 chunks area)

I'm not sure what was there originally, but it's certainly not everything

I've emailed you the recovered world zip folder

**Comment by NotStirred** [comment]
I would HIGHLY recommend you update to the latest `stable` / `stable snapshot` version if you haven't already btw
