### ISSUE TITLE
Missing block textures inside a Docker Container

### ISSUE THREAD

**Issue by luiz-otavio** [chunky-dev/chunky#1315]
I tried to make a docker container based on [yolks:java-17](https://github.com/pterodactyl/yolks/pkgs/container/yolks/25230031?tag=java_17) image to render some chunks from our application, but instead of giving us the right output which has made by testing in a local machine, it gives some missed textures.

Image from local-machine:
![0-0](https://user-images.githubusercontent.com/65752397/174498696-b9477592-1dc0-4390-a978-82441611834b.png)

Config of the local-machine:

- Java: `openjdk 17.0.2 2022-01-18 | OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) |OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)`
- GPU: NVIDIA Corporation GP104 [GeForce GTX 1060 6GB];
- CPU: Intel® Core™ i5-9400F CPU @ 2.90GHz × 6.

Image from dedicated-machine:
![0-0 (1)](https://user-images.githubusercontent.com/65752397/174498705-dec16499-1378-48be-a58c-8e83a176d4ef.png)

Config of the dedicated-machine:

- Java: [yolks:java-17](https://github.com/pterodactyl/yolks/tree/master/java/17);
- Host: 
![image](https://user-images.githubusercontent.com/65752397/174498848-83e7304b-cdf4-46a2-bfc9-4dda6b868791.png)

**Comment by luiz-otavio** [comment]
By the way, we're executing the chunky based on its CLI.

**Comment by Peregrine05** [comment]
There is probably no Minecraft installation on the dedicated machine, so there is no Minecraft version.jar from which to load resources. If you add the Minecraft version.jar to the right place on the dedicated machine (`".minecraft/versions/<version number>/<version number>.jar"`), then Chunky should auto-detect it and load from it the right textures.

**Comment by luiz-otavio** [comment]
> There is probably no Minecraft installation on the dedicated machine, so there is no Minecraft version.jar from which to load resources. If you add the Minecraft version.jar to the right place on the dedicated machine (`".minecraft/versions/<version number>/<version number>.jar"`), then Chunky should auto-detect it and load from it the right textures.

Great news! That makes sense <3

**Comment by Peregrine05** [comment]
Alternatively, you could edit the chunky.json file to manually add in the version.jar as a resource pack from anywhere in the dedicated machine.

**Comment by luiz-otavio** [comment]
> Alternatively, you could edit the chunky.json file to manually add in the version.jar as a resource pack from anywhere in the dedicated machine.

Should I do that like:
```
{
  "resource_pack": ".minecraft/versions/1.17.1/1.17.1.jar"
}
````

**Comment by luiz-otavio** [comment]
> > Alternatively, you could edit the chunky.json file to manually add in the version.jar as a resource pack from anywhere in the dedicated machine.
> 
> Should I do that like:
> 
> ```
> {
>   "resource_pack": ".minecraft/versions/1.17.1/1.17.1.jar"
> }
> ```

Oh, I found that I should use `version` instead of `resource_pack` (https://github.com/chunky-dev/chunky/blob/8a8428275678d4a0248e5e4f9f15710f301b0384/lib/src/se/llbit/chunky/launcher/LauncherSettings.java#L103)

**Comment by Peregrine05** [comment]
Edit the chunky.json file after copying the 1.19.jar file to the dedicated machine.

Change the lastTexturePack entry to something like: `"lastTexturePack": "/path/to/version.jar",`

**Comment by luiz-otavio** [comment]
Right, I'm turning on the container to test it. If it works

**Comment by luiz-otavio** [comment]
That worked!! <3

**Comment by Peregrine05** [comment]
That's good!

**Comment by luiz-otavio** [comment]
@Peregrine05, there is such a way to improve the speed of the rendering time? Currently we are working with just one core for the container and its giving us such as 20 minutes to finish almost things.

**Comment by luiz-otavio** [comment]
![image](https://user-images.githubusercontent.com/65752397/174500967-f0e5794c-215b-4f2d-8125-ab99616fc467.png)
Yep, relatively I can increase the number of colors for this

**Comment by Peregrine05** [comment]
Yes, you can improve the rendering speed by changing Chunky settings. The settings that have the most effect on render time are the canvas resolution, the ray depth, and the target SPP. However, all of them can significantly affect render quality. Canvas resolution changes render time proportionally to the number of pixels on the canvas. The target SPP also changes render time proportionally to its value. The higher the target SPP, the less noise in the image. Typically, a ray depth of five is a good default for outdoor scenes, setting it lower can result in more unrealistic lighting, but better render speed.

**Comment by Peregrine05** [comment]
There is also thread count; increase that to the maximum number of threads available on your dedicated machine. A Chunky restart will be required after changing it for the changes to take effect.

**Comment by luiz-otavio** [comment]
> Yes, you can improve the rendering speed by changing Chunky settings. The settings that have the most effect on render time are the canvas resolution, the ray depth, and the target SPP. However, all of them can significantly affect render quality. Canvas resolution changes render time proportionally to the number of pixels on the canvas. The target SPP also changes render time proportionally to its value. The higher the target SPP, the less noise in the image. Typically, a ray depth of five is a good default for outdoor scenes, setting it lower can result in more unrealistic lighting, but better render speed.

Those Chunky settings are from `chunky.json`, right?

**Comment by Peregrine05** [comment]
The canvas resolution, the ray depth, and the target SPP will be found in the scene.json file. The thread count will be found in the chunky.json file, as the `"numThreads":` entry.

**Comment by luiz-otavio** [comment]
> The canvas resolution, the ray depth, and the target SPP will be found in the scene.json file. The thread count will be found in the chunky.json file, as the `"numThreads":` entry.

There is a default value for this? Like, I'm not using this property right now, however as I gave six cores to the container, so it will use all the cores?

**Comment by Peregrine05** [comment]
It should use all the cores if you set the numThreads to 6. If it is multi-threaded, then you can set it to 12.

**Comment by luiz-otavio** [comment]
> It should use all the cores if you set the numThreads to 6. If it is multi-threaded, then you can set it to 12.

Good, it really takes another kinda speeding time
![image](https://user-images.githubusercontent.com/65752397/174501344-3e82d93e-aa07-4ef4-bac5-9a86fc3cb605.png)

**Comment by luiz-otavio** [comment]
Great, I will close it! Thanks <3

**Comment by Peregrine05** [comment]
You're welcome.
