### ISSUE TITLE
Type to delete chunks

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1316]
![image](https://user-images.githubusercontent.com/3740917/174498919-93a74b09-0a23-4ddb-b5d7-17a46c0c61cc.png)

The current checkbox can be clicked easily without reading or thinking. Various UX guides suggests making the user type a word/phrase or world name in order to delete things. Also see [How to Make Sure Users Don’t Accidentally Delete](https://uxmovement.com/buttons/how-to-make-sure-users-dont-accidentally-delete/).

Adding an undo button is also suggested but I'm unsure where we would locate this.

**Comment by Peregrine05** [comment]
Personally, I think that the current controls are enough, but there are such people. . .
Typing "Delete" in an input field to confirm is not very hard to do, either.

**Comment by jackjt8** [comment]
> Typing "Delete" in an input field to confirm is not very hard to do, either.

Why not captcha?

**Comment by leMaik** [comment]
Should we finally remove this feature? :thinking: I was against removing it before, but it seems like it would be better to not have Chunky destroy worlds.

**Comment by Peregrine05** [comment]
Keep it, but make it explicitly clear on the effects that this action will have, and make the user do an explicit series on actions (e.g. typing a string of text) to confirm the deletion.

**Comment by NotStirred** [comment]
I was, and still am, for removing the feature.

Regardless of chunky's past as a map viewer/editor, no user expects a rendering engine to modify their world in any way

**Comment by ShirleyNekoDev** [comment]
I'd suggest to move the delete feature to a separate plugin and not ship it in the main software. 
The plugin could also create backups for each modified region file.

**Comment by jackjt8** [comment]
I'm definitely for moving this into a plugin as long as it can also handle backups.

**Comment by Peregrine05** [comment]
This feature is definitely neither the most necessary nor the most used feature in Chunky, so I am also okay with its functionality being migrated to a plugin. A region backup feature will also be useful.

**Comment by leMaik** [comment]
This should now be implemented over at https://github.com/chunky-dev/chunky-editor
