### ISSUE TITLE
Disabling `Draw sun` disables sunlight in the latest snapshot

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1317]
In the latest snapshot, disabling `Draw sun` when SSS is set to Fast, High quality, or Off causes the sunlight to be completely disabled. This should not occur, as `Draw sun` is only to change the visibility of the texture of the sun on the sky. There is already a setting to disable sunlight, which is SSS: NON_LUMINOUS.

**Comment by jackjt8** [comment]
To add to why this is useful-

Previously we could disable the sun texture but still have sunlight which was useful in cases where the sun texture did not fit the skymap. While this was primarily used to to actually make the sun within a SDR skymap actually provide illumination, it could also be used to further argument HDRi skymaps.
