### ISSUE TITLE
What does chunky need to render an image?

### ISSUE THREAD

**Issue by luiz-otavio** [chunky-dev/chunky#1322]
I tried to render 2500 chunks divided into 16x16 chunks per render, but sometimes those renders were made with wrong outputs from missed blocks, chunks and more.
![unknown](https://user-images.githubusercontent.com/65752397/175189187-598ed2fa-886f-408f-9b6c-46e64ef796f6.png)

We found some logs from Chunky when its trying to render the specific location of those renders, but some outputs are doubtful?

![image](https://user-images.githubusercontent.com/65752397/175189338-f0ed3cc3-462a-4bd6-b79a-cba1fe30a534.png)

We're using the CLI from Chunky (latest) to write those renders, but we don't know if is that a world issue that the region file doesn't exist or some internal issue.

**Comment by leMaik** [comment]
So... What is the issue you're facing?

**Comment by luiz-otavio** [comment]
> So... What is the issue you're facing? The log output above doesn't show errors and the image looks good to me.

Basically some chunks are out of the image, I mean, this is one of our renders which contains exactly 16x16 chunks:
![0-35](https://user-images.githubusercontent.com/65752397/175431081-4ab5edee-a934-4577-815d-e912c61e2529.png)

**Comment by luiz-otavio** [comment]
Guys, I will close this issue because I got a resolution about this. The main problem is that the region didn't loaded as well for rendering. Thank you!
