### ISSUE TITLE
Excessive memory usage since 3d biome support was added

### ISSUE THREAD

**Issue by almrausch** [chunky-dev/chunky#1327]
It seems like the commit "Add 3d biomes and 3d blur (off by default) (#1225)" makes Chunky use drastically more memory when loading a scene. Loading scenes with more than 200k chunks has been no problem for me before, but now I run out of memory when loading scenes with as little as 20k chunks.

**Comment by jackjt8** [comment]
So after bisecting and manual testing we have been able to confirm that memory usage does increase by a significant amount after #1225. In my testing on  2.4.2 we would typically see ~1.8GB for a 4 region selection. This balloons up to 8GB for snapshots post 1225.

The trival2d structures retained size compared to next largest and "unchanged" from previous versions.

```
    Trivial2dBiomeStructure - 1GB
    Trivial2dBiomeStructure - 1GB
    Trivial2dBiomeStructure - 1GB
    Octree                  - 0.3GB
```

WORLD-TEXTURE-2D in #1329 should restore memory usage to 2.4.2 levels.

We have noticed what appears to be excessive allocation in 2.5.0 compared to 2.4.2. However tracking down exactly what is going on is so far proving difficult.
