### ISSUE TITLE
Player heads on armour stands do not render correctly

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1334]
Only occurs with non-default texture player heads from what I can tell.

Affects - `2.4.2`, `2.5.0`

![image](https://user-images.githubusercontent.com/3740917/177218430-7f156495-925e-46d7-9bbd-9d5a60796bb2.png)

![image](https://user-images.githubusercontent.com/3740917/177218440-32c3dcbb-ef60-49cc-8bb5-bf35a841c391.png)

**Comment by leMaik** [comment]
This only hapens if the player has a non-square head texture.
