### ISSUE TITLE
Biome colors are incorrect in the latest snapshot, and change depending on biomes within chunk selection

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1343]
Depending on the biomes within the chunk selection, the colors of all of the foliage change to that of one of the biomes in the chunk selection. The color changes depending on the biomes within the selection.

![Biome_incorrect_1](https://user-images.githubusercontent.com/92183530/177747120-2425476f-78ec-4c6e-8cea-596cbca741ca.png)

![Biome_incorrect_2](https://user-images.githubusercontent.com/92183530/177747203-a0aa453b-15f6-4b70-85b8-3ca0f3e844c9.png)

**Comment by Peregrine05** [comment]
![image](https://user-images.githubusercontent.com/92183530/177753729-fd6f7795-ed34-44c2-a7a2-c81035359820.png)

**Comment by Peregrine05** [comment]
Yet strangely enough, some 1.18 worlds do work normally.

**Comment by NotStirred** [comment]
Ok I see how this happened, quite a weird one to find.
Basically we were always loading the palette structure as 3d, even if 3d biomes was disabled.

Will push a PR
![image](https://user-images.githubusercontent.com/16853282/178032198-b170ba2b-cb31-4052-9f38-ba8ef674cc13.png)
