### ISSUE TITLE
Rendering an image inside a minecraft server

### ISSUE THREAD

**Issue by luiz-otavio** [chunky-dev/chunky#1356]
Look who have back! Right, I think it's a normal question about the rendering, so, there is such a way to render [those](https://github.com/chunky-dev/chunky/issues/1315#issue-1276157098) images inside a minecraft server? I mean, like getting a public API to manipulate these things.

**Comment by NotStirred** [comment]
There are problems (especially on windows) with reading region files that are currently being accessed by the game, that may be an issue. Dynmap seems to manage though, so maybe not

**Comment by luiz-otavio** [comment]
Right, that really makes sense.
