### ISSUE TITLE
Player heads are no longer positioned correctly in the latest snapshot.

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1372]
For example, in a previous snapshot, the heads were positioned like so:
![image](https://user-images.githubusercontent.com/92183530/179549925-384f27b4-9953-4237-8029-feff48560b7e.png)

However, in the latest snapshot, the heads are positioned like so:
![image](https://user-images.githubusercontent.com/92183530/179550201-ba212681-f05b-494e-b0f2-f04804964198.png)

**Comment by leMaik** [comment]
Probably a regression from #1338
