### ISSUE TITLE
Add a dropdown menu to the launcher to select update sites.

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1392]
Add a dropdown menu button next to the `Update site` input field to select common update sites, such as `https://chunkyupdate.lemaik.de`, `https://chunky-pr.lemaik.de`, `https://chunkyupdate.llbit.se`, etc. This will make it easier for users to select the Chunky version that they want to download. In addition, add tooltips to each update site so that new users an get an idea of what they are selecting.

**Comment by leMaik** [comment]
There's no point in adding this. chunky-pr.lemaik.de will replace my update site eventually, Chunky 1.x is not maintained and I don't really see a reason for using it.
