### ISSUE TITLE
Regression: missing dependencies in chunky-core release pom file (maven repository)

### ISSUE THREAD

**Issue by ShirleyNekoDev** [chunky-dev/chunky#1397]
#1390 broke list of Chunky's dependencies in the released pom file

compare
https://nexus.wertarbyte.com/repository/leMaik/se/llbit/chunky-core/2.5.0-SNAPSHOT/chunky-core-2.5.0-20220304.113004-103.pom
vs.
https://nexus.wertarbyte.com/repository/leMaik/se/llbit/chunky-core/2.5.0-SNAPSHOT/chunky-core-2.5.0-20220726.102943-104.pom

**Comment by leMaik** [comment]
#1110 broke it, we just published it with a wrong name

**Comment by ShirleyNekoDev** [comment]
Duplicate of #1394
