### ISSUE TITLE
Scene directory can't be opened after saving a scene until the scene panel is toggled

### ISSUE THREAD

**Issue by leMaik** [chunky-dev/chunky#1398]

**Comment by leMaik** [comment]
@chunky-dev/qa Do any of you remember how this can be reproduced?

**Comment by jackjt8** [comment]
Unable to reproduce this on Windows 11 and with `Chunky 2.5.0-DEV.171.g3126617`.

1. Select chunk
2. New Scene from selection
3. File > Save As ...
4. Navigate to `scenes directory` via a file browser

---

4. File > Load Scene
6. Scene Manager
7.  `Open scenes directory`

Both methods work and I have not toggled the Scene Panel.
