### ISSUE TITLE
Add a control to hide the player icons in the `Map` tab.

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1405]
If a very great number of players has joined a particular world, then the player location icons on the map view can hide much of the ground and be quite annoying. An option to hide them could be worthwhile. Examples of this effect are below.

![image](https://user-images.githubusercontent.com/92183530/182246708-571aec4f-46e5-4a39-9ed2-b65d6e1dcc9a.png)

![image](https://user-images.githubusercontent.com/92183530/182246733-d6329f9d-44d3-4a2c-a0ce-025842bedbd0.png)

**Comment by NotStirred** [comment]
Closed by #1419
