### ISSUE TITLE
Hide/disable `Render Preview` if no chunks are loaded by default

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1407]
I'm unsure if JavaFX allows us to hide/show/disable(grey out) tabs retroactively like this.

However I have noticed a number of new users are confused by the loading process. If we can hide the `Render Preview` while no chunks are currently loaded, or to show a tooltip on a greyed out tab (stating to select chunks an then click on `load...` or `new scene...`), this may greatly improve new user experience.

Of course, we could still have an option to keep the `Render Preview` enabled at all times in case anyone wishes it to be.

**Comment by Peregrine05** [comment]
There is this, though.

![preview_no_chunks](https://user-images.githubusercontent.com/92183530/182402222-c86d7fc6-3b15-4789-9450-4a5650316b54.png)

**Comment by jackjt8** [comment]
For some reason that doesn't always seem to show up and users are confused.

**Comment by Peregrine05** [comment]
This might be a 2.5.0 snapshot-only feature. Let me check.

**Comment by leMaik** [comment]
We should not hide it, but just grey it out. If we hide it, users might not know that it is there. I actually like the helpful message we have now, maybe we should just ensure that it is always displayed.

**Comment by jackjt8** [comment]
Unable to reproduce
