### ISSUE TITLE
Save dump once every N frames - Bad UI

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1432]
![image](https://user-images.githubusercontent.com/3740917/184323068-f807a929-d5c3-4065-8a35-2c3e4dc7d1b9.png)

We effectively have two controls for one thing. All other multi-choice drop downs have an `off`/`none` state. This option is making documentation annoying.

Suggest reworking this such that it can just be one dropdown with an off state.

**Comment by leMaik** [comment]
"Save dump every Never frames" would be strange :thinking:

**Comment by jackjt8** [comment]
Of course we would need to rework the option label to allow this.

**Comment by Peregrine05** [comment]
Autosave frequency: {Never, 100, 500, etc.} SPP

**Comment by jackjt8** [comment]
> Autosave frequency: {Never, 100, 500, etc.} SPP OR
> 
> * [ ]  Autosave frequency: {10, 50, 100, 500, etc.} SPP

The second option would just repeat the same issue we have currently whereby there are two different control types for the same label. The first option would not only solve this issue but it does so while being worded well.
