### ISSUE TITLE
Notify the user that the scenes list is loading.

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1441]
If the scenes list is very long, then it can take much time to finish loading all of the scenes after the `Load` button is clicked. The worlds list also takes long to load after the `Change world` button is clicked; however, it notifies the user that the worlds list is being loaded with the text `Loading worlds list...`. The scenes list should notify the user with similar text, such as, `Loading scenes list...`, instead of remaining closed until the scenes list is loaded.

**Comment by leMaik** [comment]
I merged that PR too early :sweat_smile:  This doesn't work yet.
