### ISSUE TITLE
Changing `Apparent sky brightness` changes the apparent brightness of the sun texture

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1471]
This is only apparent in the path-traced render, and not in the preview. Ideally, this should not happen.

**Comment by jackjt8** [comment]
While we should aim to minimise the differences between the Preview and Path-Traced Render I would also pose to mention that the setting in question is dubbed `Apparent sky brightness` and it has a significant impact to the rendering of the `Sun`. Either this particular option needs to be named accordingly or we need to decouple and create a separate control for the Sun.

Simulated Apparent:0.01 preview 
![image](https://user-images.githubusercontent.com/3740917/196011099-a96581c8-5e32-413b-a07b-7984356cb1f7.png)
Simulated Apparent:0.01 render
![image](https://user-images.githubusercontent.com/3740917/196011102-6a06d856-1132-40ad-9aaa-12b185dddccf.png)


Black Apparent:1.0 preview
![image](https://user-images.githubusercontent.com/3740917/196011222-d3bfb035-aa17-40eb-83b6-53342e107818.png)

Black Apparent:1.0 render
![image](https://user-images.githubusercontent.com/3740917/196011228-880b45f1-ac4f-4151-9cb8-012b22ffad83.png)


Setting `Apparent sky brightness` to 0.0 actually disables the Sun texture as well.

---

Ideally that should not occur.
