### ISSUE TITLE
Independent skymap exposure control

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1472]
Different skymaps, mainly HDRi's, have vastly different brightness levels. There are a few benefits when it comes to memory usage and performance when it comes to using pngs vs HDRi's.

png varient 16SPP:
![image](https://user-images.githubusercontent.com/3740917/196012084-757730e8-a611-4ee0-a737-987bc8b7c861.png)

HDRi varient 16SPP:
![image](https://user-images.githubusercontent.com/3740917/196012091-a68ab549-4370-495d-a993-c15f3b2c8d5f.png)

In the case you wish to switch from png to HDRi, or HDRi to HDRi, and you do not wish to alter your settings too much... you can't. Opposed to having a single control which can be used to alter how the changed element interacts with the scene you are required to edit multiple:

`Sky brightness`, `Apparent sky brightness`, `Emitter intensity`, `Sun intensity`, `Sun luminosity`, `Exposure`.

Each of those settings have knock-on effects which take time to iron out.

He's an example HDRi:
![image](https://user-images.githubusercontent.com/3740917/196012241-bf655f03-b3e6-4662-8e91-1f747f181861.png)

This is a crude "fix" by just adjusting the exposure:
![image](https://user-images.githubusercontent.com/3740917/196012261-5f3d3085-a1c8-4a66-a42d-ab8aca90ea95.png)

You would still need to re-adjust all the other settings.

---

Having a single control that can be used to quickly adjust the exposure, both brightness and apparent, of just the skymap would increase flexibility and reduce time spent tweaking all the ~~spaghetti~~ various interconnected settings.

---

Related to #1471

**Comment by Peregrine05** [comment]
A checkbox to bind the two Sky brightness controls to each other is a possible solution.

**Comment by jackjt8** [comment]
> A checkbox to bind the two Sky brightness controls to each other is a possible solution.

What happens when you "bind" the two controls if the values are different? Are we going to force the values to be the same or are we going to attempt to adjust them while maintaining the ratio?

What happens when you unbind the controls? Will the values return to their unbound state?

How will we explain this behaviour to the user?

--

I understand that this is probably how we will achieve this effect however in terms of complexity a separate option that can be used to adjust skymap exposure would be beneficial. Simulating the proposed bound Sky brightness controls means we can often end up working with values as low as 0.025. Our minimum is 0.01(1) for slider controls. If we are to use this bound solution we would be restricting how quickly users can make fine adjustments. If we do place skymap exposure independently, the user would just need to adjust it once to get the approximate value set. Fine adjustments could then be made within the Lighting tab from a basis of 1.0 which would make adjustments quick and easy.
