### ISSUE TITLE
[Block models branch] Glowstone does not emit any light

### ISSUE THREAD

**Issue by NJDaeger** [chunky-dev/chunky#1475]
My settings were:

ESS: ALL
Emittance of glowstone was nonzero
Other lights in the scene are working fine.

Glowstone blocks in this scene
https://media.discordapp.net/attachments/545374333883777037/1030572567498596402/unknown.png

How they rendered
https://media.discordapp.net/attachments/545374333883777037/1030572567901245540/default_2022-10-14_14-06-33_2-50.denoised.png

**Comment by HackerDaGreat57** [comment]
If you are talking about PBR I'm not sure if this is supported yet.

If you mean you want the whole block to glow, then you can simply just open the 'Materials' section of the left pane and look for `minecraft:glowstone` (or `minecraft:iron_block` by the looks of it) and set the emission level to like 0.03. Scale up or down until you're happy with the result.

**Comment by leMaik** [comment]
When I tried to reproduce this (with default settings and with ESS: ALL), glowstone emitted light. I guess this has been fixed at some point.
