### ISSUE TITLE
`.tiff` exports two pages

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#1491]
When importing `.tiff` files produced within Chunky in an application like GIMP the dialog shows that there are two pages

![image](https://user-images.githubusercontent.com/3740917/197358337-8f1aeafe-5d77-4dee-a62e-c6680e7d6032.png)

However, GIMP is unable to import a second page

![image](https://user-images.githubusercontent.com/3740917/197358413-f269009f-ea33-4cab-800d-01b0a89bb3be.png)

---

Pretty sure the `.tiff` export option is incorrectly applying the flag for multi-page tiff images.

**Comment by jackjt8** [comment]
![image](https://user-images.githubusercontent.com/3740917/197358497-1ca34518-f0f6-43fe-b18f-b9265eaa9565.png)

And another error...

**Comment by ShirleyNekoDev** [comment]
IrfanView detects 3 pages
![image](https://user-images.githubusercontent.com/16897056/197397375-10db4508-bd35-4436-a2cb-13743d79cbcb.png)
