### ISSUE TITLE
None of the scene options visible in Chunky 2.5.x snapshot GUI

### ISSUE THREAD

**Issue by AlcoRS11** [chunky-dev/chunky#1499]
When loading a scene in 2.5.x, none of the options such as lighting, skies, camera settings, etc are visible on the sidebar in the GUI. All of the options and settings are visible in 2.4.x. As a result, I cannot use the snapshot builds since they're basically unusable without the controls.
**2.5.x**
![image](https://user-images.githubusercontent.com/11202393/198203809-a7e17891-cf0a-4387-80a8-00dd7676ec4a.png)

**2.4.2**
![image](https://user-images.githubusercontent.com/11202393/198204437-ae0dfe7f-d9b1-4d4c-a304-004517ad1dec.png)

**Comment by Peregrine05** [comment]
It looks as though you are loading the version of the Bloom plugin that is only compatible with 2.4.x. If you attempt to load it in 2.5.x, Chunky will not be able to load the render controls tabs. Either disable the plugin from loading, or download the newer version of the plugin that is compatible with only 2.5.x.
https://chunky-dev.github.io/docs/plugins/plugin_list/#bloom-plugin
https://github.com/aTom3333/chunky-bloom-plugin/releases

As a side note, the latest stable release of Chunky is 2.4.4.

**Comment by Peregrine05** [comment]
I am closing this due to lack of response.
