### ISSUE TITLE
Potential camera clipping with parallel projection and transparent sky.

### ISSUE THREAD

**Issue by ThatRedox** [chunky-dev/chunky#1507]
From discord: https://discord.com/channels/541221265512464394/571769711402942467/1046999294479179786
![SpawnMigration8KIsometric (Small)](https://user-images.githubusercontent.com/42661490/204978466-055c0d1e-005c-4ced-8105-d32f20e49657.png)
![image](https://user-images.githubusercontent.com/42661490/204978501-6b57a7ed-8dc6-47de-8c79-c1d097dab139.png)

Earlier report from discord: https://discord.com/channels/541221265512464394/571769711402942467/966447335783690261

Restarting Chunky seems to have fixed it. Having trouble reproducing.

**Comment by leMaik** [comment]
Possibly related to #942
