### ISSUE TITLE
Add a way to configure beacon beams in the Materials tab

### ISSUE THREAD

**Issue by chadtello** [chunky-dev/chunky#1511]
It would be nice if we could configure beacon beams in materials. Also can we have an option to configure the beacon beam height?

**Comment by Peregrine05** [comment]
Beacon beams already have material controls. Select the beacon beam in the `Entities` tab, and then adjust its material properties and its size and height. The `Metalness` control is only available in the `Snapshot` release.
https://chunky-dev.github.io/docs/reference/user_interface/render_controls/entities/#beacon-beam-controls
