### ISSUE TITLE
Iron trapdoors (possibly others?) transparent / colored like the sky in render

### ISSUE THREAD

**Issue by Mega0407** [chunky-dev/chunky#1523]
Hi, I tried rendering this scene but the trapdoors are always transparent-ish and colored like the sky.
Default settings plus I set sky to solid color and changed camera POV and canvas size.
This also happens with default Minecraft sky. I'm unsure if this happens with other trapdoor types.
I was rendering a build from 1.12 pasted into a void world in 1.16.5 and exported and put in chunky.

![default_2023-01-04_16-40-09-1000](https://user-images.githubusercontent.com/99270686/210601703-a7d95d88-4319-451d-97f7-a2ec9ce16bdc.png)

![Screenshot 2023-01-04 171520](https://user-images.githubusercontent.com/99270686/210601808-48e1acf0-31c6-4eda-b398-ffd6e93e96a6.jpg)

**Comment by Peregrine05** [comment]
In the `Materials` tab, set the `Metalness` and `Specular` of Iron trapdoors to a lower value, such as *0*, to reduce or eliminate this effect. They look as though they are colored like the sky because they are very reflective by default.

**Comment by Mega0407** [comment]
> In the `Materials` tab, set the `Metalness` and `Specular` of Iron trapdoors to a lower value, such as _0_, to reduce or eliminate this effect. They look as though they are colored like the sky because they are very reflective by default.

Thank you, specular was 0 but metalness was really high.  Issue solved
