### ISSUE TITLE
Minecraft 23w07a (and earlier 1.20 snapshots)

### ISSUE THREAD

**Issue by leMaik** [chunky-dev/chunky#1550]
This issue bundles all updates required to support Minecraft 23w07a. For future snapshots, we'll create issues per snapshot, as we used to do since 1.19 snapshot phase.

- [x] acacia_hanging_sign
- [x] acacia_wall_hanging_sign
- [x] bamboo_block
- [x] bamboo_button
- [x] bamboo_door
- [x] bamboo_fence
- [x] bamboo_fence_gate
- [x] bamboo_hanging_sign
- [x] bamboo_mosaic
- [x] bamboo_mosaic_slab
- [x] bamboo_mosaic_stairs
- [x] bamboo_planks
- [x] bamboo_pressure_plate
- [x] bamboo_sign
- [x] bamboo_slab
- [x] bamboo_stairs
- [x] bamboo_trapdoor
- [x] bamboo_wall_hanging_sign
- [x] bamboo_wall_sign
- [x] birch_hanging_sign
- [x] birch_wall_hanging_sign
- [x] cherry_button
- [x] cherry_door
- [x] cherry_fence
- [x] cherry_fence_gate
- [x] cherry_hanging_sign
- [x] cherry_leaves
- [x] cherry_log
- [x] cherry_planks
- [x] cherry_pressure_plate
- [x] cherry_sapling
- [x] cherry_sign
- [x] cherry_slab
- [x] cherry_stairs
- [x] cherry_trapdoor
- [x] cherry_wall_hanging_sign
- [x] cherry_wall_sign
- [x] cherry_wood
- [x] chiseled_bookshelf
- [x] crimson_hanging_sign
- [x] crimson_wall_hanging_sign
- [x] dark_oak_hanging_sign
- [x] dark_oak_wall_hanging_sign
- [x] decorated_pot
- [x] jungle_hanging_sign
- [x] jungle_wall_hanging_sign
- [x] mangrove_hanging_sign
- [x] mangrove_wall_hanging_sign
- [x] oak_hanging_sign
- [x] oak_wall_hanging_sign
- [x] piglin_head
- [x] piglin_wall_head
- [x] pink_petals
- [x] potted_cherry_sapling
- [x] potted_torchflower
- [x] spruce_hanging_sign
- [x] spruce_wall_hanging_sign
- [x] stripped_bamboo_block
- [x] stripped_cherry_log
- [x] stripped_cherry_wood
- [x] suspicious_sand
- [x] torchflower
- [x] torchflower_crop
- [x] warped_hanging_sign
- [x] warped_wall_hanging_sign

**Comment by ShirleyNekoDev** [comment]
Do we want to move hanging signs into a separate issue?

**Comment by leMaik** [comment]
Whoops... Not done yet :sweat_smile:
