### ISSUE TITLE
Minecraft 23w12a Snapshot Features

### ISSUE THREAD

**Issue by ShirleyNekoDev** [chunky-dev/chunky#1563]
This is also a follow up issue for snapshot changes after #1550

- [x] new decorated pot spout model
- [x] new pottery shards
- [x] calibrated sculk sensor block
- [x] sus gravel
- [x] pitcher plant
- [x] pitcher crop
- [x] sniffer egg
- [x] text on both sides of a sign
- [x] flowerbed model changes

Possible new entities:
- [ ] armor trims on armor stand entities
- [ ] display entity

**Comment by leMaik** [comment]
The decorated pot model was updated in #1602 :tada:
