### ISSUE TITLE
Camera Renaming

### ISSUE THREAD

**Issue by PlasticTasticc** [chunky-dev/chunky#1565]
When renaming a camera, as it currently is, it creates a new camera instead of actually renaming. I'd like to be able to just rename a camera instead of ending up with 2 identical cameras.

**Comment by leMaik** [comment]
Snapshot only or in 2.4.4 too?

**Comment by PlasticTasticc** [comment]
> Snapshot only or in 2.4.4 too?

Dunno, as far as I can remember it's always been like this.
