### ISSUE TITLE
Chunky won't start rendering large images

### ISSUE THREAD

**Issue by Entropy159** [chunky-dev/chunky#1590]
I am trying to render a city in the night at 1920x1080, but whenever I hit start it freezes and won't render. If I half the scale twice, it renders slow but it works. It also renders if I turn off the emitters. Anyone have any ideas?

**Comment by Peregrine05** [comment]
Is Emitter Sampling Strategy enabled? (Is it set to anything other than `NONE`?)

**Comment by Entropy159** [comment]
Yes, I have it set to "All".

**Comment by Peregrine05** [comment]
When ESS is set to `ALL`, and there are many emitters in the scene (such as in a city), then render speed will be drastically decreased. Chunky is rendering the scene at 1920x1080 resolution, but each frame requires so much time to render that it looks as though Chunky has frozen. Decreasing the resolution decreases the amount of time required for one frame to be rendered, which makes Chunky appear slow, but at least responsive. Disabling emitters also disables ESS, causing render speeds to increase. Try setting ESS to `ONE` or `ONE_BLOCK` to increase render speed while still benefiting from reduced noise (albeit to a lesser extent). You may not see the `ONE_BLOCK` option if you are not on a snapshot release.

**Comment by Entropy159** [comment]
Is one or one block better?

**Comment by Peregrine05** [comment]
`ONE_BLOCK` typically requires less time to converge (reduce noise) to the same level as `ONE`, but each frame will require more time to render. There are some example renders on this page.
https://chunky-dev.github.io/docs/snapshot/user_guides/introduction/next_event_estimation/#emitter-sampling-strategy-ess

**Comment by Entropy159** [comment]
Thanks! It works now.

**Comment by Peregrine05** [comment]
You're welcome. I shall close this issue, but feel free to reopen it or open a new one if you have more issues.
