### ISSUE TITLE
Opening the `Advanced` tab attempts to refresh the scene

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1594]
If the `Advanced` tab is opened for the first time after starting Chunky, it will attempt to refresh the scene, which may be problematic if a render is already in progress.

I notice thie behavior in the snapshot release; I am not sure if it affects stable as well.

**Comment by ThatRedox** [comment]
This affects both snapshot and stable for different reasons.
In snapshot, it appears to be a soft refresh from the octree implementation control.
In stable, it appears to be a refresh from setting `preventNormalEmitterWithSampling` (and possibly others).

**Comment by ThatRedox** [comment]
For stable, it looks like #1237 needs to be backported.

**Comment by leMaik** [comment]
Is this issue fixed in both versions by merging both PRs?

**Comment by Peregrine05** [comment]
This issue is fixed on both master and 2.4.x.
