### ISSUE TITLE
Newest snapshot (2.5.0-SNAPSHOT.291.gf109a518) SPP incorrect

### ISSUE THREAD

**Issue by Entropy159** [chunky-dev/chunky#1647]
I've noticed with snapshot 2.5.0-SNAPSHOT.291.gf109a518 of Chunky, when I render the SPP progresses as normal, but once it reaches 4 it proceeds to render, but instead of moving 1 SPP forward it moves 10, even though it only rendered 1. It goes 1, 2, 3, 4, 10, 20, 30, 40, etc. This is annoying because instead of rendering 1024 SPP, the value I set it to, it renders 106. If this could be fixed in the next snapshot, that would be great.

**Comment by JustinTimeCuber** [comment]
This is ray branching, it's more or less doing multiple SPP simultaneously to increase render speed. If you want to disable this feature, you can set `Branch count` to 1 in the `Advanced` tab.
