### ISSUE TITLE
Support LZ4 compressed region files

### ISSUE THREAD

**Issue by ShirleyNekoDev** [chunky-dev/chunky#1684]
Snapshot [24w04a](https://www.minecraft.net/en-us/article/minecraft-snapshot-24w04a) added LZ4 as new region-file-compression.

The article states that there are 2 possible values: deflate (zlib) and lz4 - we also support gzip, probably from older versions (not sure)?

Relevant code:
- https://github.com/chunky-dev/chunky/blob/master/chunky/src/java/se/llbit/chunky/world/region/MCRegion.java#L347
- https://github.com/chunky-dev/chunky/blob/master/chunky/src/java/se/llbit/chunky/world/ChunkDataSource.java#L58

This feature requires an additional dependency, because Java JDK does not ship LZ4 decoders.
Probably one of those: [LZ4 Java](https://github.com/lz4/lz4-java) or [Kanzi](https://github.com/flanglet/kanzi).

**Comment by leMaik** [comment]
Gzip is unused by Minecraft but technically an allowed value of the file format.

**Comment by NotStirred** [comment]
gzip is used in cubic chunks region files
