### ISSUE TITLE
Stripped logs cannot be rendered

### ISSUE THREAD

**Issue by Zhou-Shilin** [chunky-dev/chunky#1690]
Stripped logs cannot be rendered. (1.20.1)
![321E4C2E-0A20-40C4-805B-0D6A8FD56086](https://github.com/chunky-dev/chunky/assets/86581525/a174704a-ece5-44b5-9aa7-16eef1685599)
![6D9875D0-BA83-4ADE-917D-BD16F2494A62](https://github.com/chunky-dev/chunky/assets/86581525/0803d0cf-fa61-466b-9b9c-abacf2368e50)

**Comment by Peregrine05** [comment]
Load a recent Minecraft version.jar as a resource pack in Chunky.
https://chunky-dev.github.io/docs/support/troubleshooting/#blocks-rendered-in-chunky-use-incorrect-textures-or-render-as-black-with-a-red-x

**Comment by Zhou-Shilin** [comment]
> Load a recent Minecraft version.jar as a resource pack in Chunky.
> https://chunky-dev.github.io/docs/support/troubleshooting/#blocks-rendered-in-chunky-use-incorrect-textures-or-render-as-black-with-a-red-x

Thanks. I'll try it tomorrow.
