### ISSUE TITLE
Other Types Of Display Entity Support (Item Displays & Text Displays)

### ISSUE THREAD

**Issue by KillerWhaleK1045** [chunky-dev/chunky#1695]
Hello! i recently saw that you guys have initial support for block display entities, however i was wondering if there could be any problems with different forms of display entities? (such as item displays & text displays, and notably with custom heads). and is it possible to implement? or will that not be possible currently?

photos included is of item displays using custom heads:
![2024-03-02_22 18 40](https://github.com/chunky-dev/chunky/assets/162002922/04f9d133-ff4d-43f4-83a3-b1ab2a458cb9)
![2024-03-02_22 27 04](https://github.com/chunky-dev/chunky/assets/162002922/530df891-6f1c-4644-bf76-dee712b4af2d)

**Comment by leMaik** [comment]
This will all be supported. See #1691 (but thanks a lot for the examples!)
