### ISSUE TITLE
Fancier Translucency makes black pixels transparent

### ISSUE THREAD

**Issue by ThisIsBrady** [chunky-dev/chunky#1718]
When Fancier translucency is enabled, fully black, non-transparent pixels on textures turn transparent. It will render correctly in preview and turn transparent in the actual renderer.
Only affects RGB value (0, 0, 0).

Fancier Translucency enabled:
(Invisible Sheep eye, invisible player head, and artifacts on player's legs)
![default_2024-04-05_16-58-08-100](https://github.com/chunky-dev/chunky/assets/30638248/78ee27ca-8fa4-4f7f-9efb-9d412c2eef97)

Fancier Translucency disabled:
(Sheep eye and player head is there)
![fancier-disabled](https://github.com/chunky-dev/chunky/assets/30638248/c4096499-1931-4920-be68-b128f62a145f)

**Comment by leMaik** [comment]
Pinging @JustinTimeCuber :pray:

**Comment by JustinTimeCuber** [comment]
I think this is a 0^0 related issue, I'll fix it this weekend

**Comment by leMaik** [comment]
This bug can also be easily reproduced with the `UNKNOWN` texture (sheep are not in the game yet).

**Comment by JustinTimeCuber** [comment]
I pushed a fix on a [branch](https://github.com/JustinTimeCuber/chunky/tree/1718-fix), but I need to test it a bit more.
