### ISSUE TITLE
Cherry leaves and both variants of azalea leaves are unaffected by material property changes

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1745]
Any change to the material properties of cherry leaves and both variants of azalea leaves is not displayed in the render preview, as though the change had no effect at all. 

The three blocks mentioned above are the ones that I have noticed exhibit this bug, but there may be others. All three blocks are `UntintedLeaves`.

**Comment by leMaik** [comment]
`UntintedLeaves` doesn't inherit from the (useless) `MinecraftBlock` block class and hence doesn't have the `minecraft:` prefix in the block name so the material settings are not applied.

We should get rid of `MinecraftBlock`, it leads to unwanted prefixes when using data packs (`minecraft:` is added to _any_ block).

**Comment by leMaik** [comment]
The same bug might apply to `spore_blossom` as well.
