### ISSUE TITLE
Time elapsed for an operation not shown

### ISSUE THREAD

**Issue by Enderdodo974** [chunky-dev/chunky#1754]
The title says it all. The time elapsed when **Loading Chunks** and **Finalizing Octree** is not displayed.
However, the time elapsed when **Rendering** is.

During chunk loading:
![image](https://github.com/user-attachments/assets/3a3bc7fa-b519-4e94-96ba-b8c7471017e4)

During octree creation:
![image](https://github.com/user-attachments/assets/9f6f7a4e-0965-4848-87ab-8964ff4438ab)

During rendering:
![image](https://github.com/user-attachments/assets/86888a17-dc17-4e83-8375-128be125797a)

**Comment by NotStirred** [comment]
Why was this closed?

**Comment by Enderdodo974** [comment]
I thought this issue was resolved by the commits above but forgot about the PR 😅

**Comment by NotStirred** [comment]
:+1: the pr is linked so the issue will auto-close once merged

**Comment by leMaik** [comment]
Just merged the PR, so it will be in the snapshot in a few minutes.
