### ISSUE TITLE
CPU utilisation when generating chunks

### ISSUE THREAD

**Issue by anhilde** [chunky-dev/chunky#1758]
Hallo, I use a spigot-1.21.1 minecraft server and have installed chunky Chunky-1.4.10.jar. Generally chunky works but generation takes a very long time. I have a Ryzen 5 5700G Cpu, eight cores, 16 threads. I have set the radius to 10000 blocks. when running chunky the CPU load never goes over 20% (checked using btop).  The java process is started with XMS and XMX set to 16Gb. Is there any way to configure to use more threads for chunky?

**Comment by Peregrine05** [comment]
You are at the wrong repository. Go to https://github.com/pop4959/Chunky instead.
