### ISSUE TITLE
World Height Issue and Heads missing

### ISSUE THREAD

**Issue by Chrisi06** [chunky-dev/chunky#1767]
I am using the latest version of chunky and have javafx and javajdk21 installed. Chunky works fine so far, but there are two problems. For some reason heads for decoration are missing and even though I configured the world height so that it begins at -64, the program cuts everything away beneath the height of 0.

**Comment by jackjt8** [comment]
There are two different controls for Y level in Chunky.

There is the `Map View` `Min/Max Y level` which controls what you see within the 2D view of the world, controlled via the right control panel 
![image](https://github.com/user-attachments/assets/141834ab-d7ad-4d54-9c81-a99a4e12a039)

Typically for Scenes/3D view you want to edit the `Y min/max clip` under the `Scene` tab in the left control panel 
![image](https://github.com/user-attachments/assets/0c9b907a-db06-4524-84e9-1ce279b2293a) - This is a common issue which is something we are trying to resolve by auto-reading the world height as it keeps going to 0 to 256 when it shouldn't. You might need to update Chunky depending on the version you have.

**Comment by leMaik** [comment]
Regarding the heads... Are you using the latest snapshot? Chunky 2.4.6 doesn't support heads from 1.21

Regarding the y level: #1741 which I do have a fix almost ready to be PR'd
