### ISSUE TITLE
24w40a

### ISSUE THREAD

**Issue by Peregrine05** [chunky-dev/chunky#1776]
24w40a introduces new blocks and biomes. https://minecraft.wiki/w/Java_Edition_24w40a#Experimental

- [x] Pale Garden biome (temperature 0.7, downfall 0.8, variation of the dark forst biome)

Blocks:
- [x] Creaking heart
- [x] Pale hanging moss
- [x] Pale moss block
- [x] Pale moss carpet
- [x] Pale oak button
- [x] Pale oak door
- [x] Pale oak fence
- [x] Pale oak fence gate
- [x] Pale oak hanging sign
- [x] Pale oak leaves
- [x] Pale oak log
- [x] Pale oak planks
- [x] Pale oak pressure plate
- [x] Pale oak  sapling
- [x] Pale oak sign
- [x] Pale oak slab
- [x] Pale oak stairs
- [x] Pale oak trapdoor
- [x] Pale oak wall hanging sign
- [x] Pale oak hanging sign
- [x] Pale oak wood
- [x] Potted pale oak sapling
- [x] Stripped pale oak log
- [x] Stripped pale oak wood

**Comment by leMaik** [comment]
I already wondered when they'd start to add new blocks. I'll look through the other snapshots, seems like the redstone torch changed, too. 

Note that I will not backport 1.21+ support to Chunky 2.4
