### ISSUE TITLE
Custom block models in 14w06b

### ISSUE THREAD

**Issue by abonander** [chunky-dev/chunky#254]
This concerns the following reddit post:

http://www.reddit.com/r/Minecraft/comments/1x8kwi/the_undocumented_snapshot_feature/

This some interesting news for us. Resource packs can now include custom block models. This isn't just another feature to implement. We can make use of this.

If they refactor Minecraft to have a default resource pack with block models instead of having them hardcoded, we don't have to hardcode our own block models into the renderer. We can just import them from the default or selected resource pack.

Looking at the assets/models folder in 14w06b.jar, it doesn't look like they've ported the basic block model, and only some of the special blocks have been ported. But this is still a snapshot. If this becomes standard we could have some cool new functionality to support.

**Comment by techkid6** [comment]
I hate to discuss a closed issue, but, three years later, it seems like the Mojang models are here to stay and that mod-makers are encouraged to use them.  What would be the chances of at least supporting the Mojang JSON format in the future?

**Comment by AEnterprise** [comment]
supporting the mojang json format would be nice (allowing resourcepacks and such as well) but if you do that would you maybe also look at the forge format? i'm pretty sure some of the forge dev team would be more then happy to help you with that.

the forge format isn't all that different from the vanilla format but has a few differences that allow shorter json files and grouping of some changes

**Comment by llbit** [comment]
I changed my mind about the custom block models some time ago. I think Chunky should absolutely support this.

I did start working on a renderer for Minecraft's model format three months ago however I have been swamped with other deadlines since then so I got totally blocked on that.

I might re-open this issue, can't remember if there is another more recent one addressing this issue.
