### ISSUE TITLE
Fullscreen mode (preview window) does not work on multi-monitor setups

### ISSUE THREAD

**Issue by JochemKuijpers** [chunky-dev/chunky#285]
As the title states, pressing U to switch to Fullscreen Mode will scale the window to the size of the primary window. I'm currently rendering a dual-screen (2x 1080p) wallpaper image and I would like to see this in fullscreen on both monitors.

I'm assuming it's a small fix, I might even do it myself if I can find the time.

**Comment by leMaik** [comment]
I'll close this as Chunky has a single-window UI now :upside_down_face:

**Comment by HackerDaGreat57** [comment]
Geez.... talk about **ancient** discussions
