### ISSUE TITLE
Two Suns Bug

### ISSUE THREAD

**Issue by ghost** [chunky-dev/chunky#319]
Sometimes, when I run a render, usually with a panoramic camera (though it shouldn't matter), my image has two suns. This only happens when I save a render and later continue it -- there is one sun before and two afterward. When I check on the settings, the sun position is still set to where the original sun is, but light seems to be coming from the second sun. I am running Chunky 1.3.5 in Windows 8

Example Images:
https://i.imgur.com/UTmsaP0.jpg
https://i.imgur.com/UtjAeQe.jpg

**Comment by leMaik** [comment]
This was probably caused by the sun position not being loaded correctly. Seems to be fixed.
