### ISSUE TITLE
Plugin API and Plugin Manager

### ISSUE THREAD

**Issue by llbit** [chunky-dev/chunky#336]
Rather than making the core Chunky code more complex by adding new options for new rendering modes it would be nice if Chunky had a plugin API, where new rendering modes could be enabled via plugins instead.

**Comment by llbit** [comment]
Plugin support would really need some form of plugin crypot signing.

**Comment by NJDaeger** [comment]
Will we see this in 1.4 possibly? Or no chance?

**Comment by llbit** [comment]
@NJDaeger I'm aiming to include an unsupported beta version of plugins in the 1.4.0 release. A more complete and supported version of plugins will be added in a later releases. I think it will take a while to evolve the plugin API to be practical for all the things that could potentially be done through plugins.

**Comment by AEnterprise** [comment]
maybe a sugestion to go with this: defining blocks with json files? it would allow to easely add (simple) mod blocks

**Comment by llbit** [comment]
@AEnterprise the whole block rendering system should be changed so that plugins can tweak it.

**Comment by leMaik** [comment]
I'd say this is done. The plugin system has been there for a long time and now plugins can also register block providers and thus blocks.
