### ISSUE TITLE
[Launcher] Use Minecraft's Java runtime if available

### ISSUE THREAD

**Issue by llbit** [chunky-dev/chunky#339]
Minecraft now ships with its own Java runtime. We can reuse that Java runtime when launching Chunky. This should solve some problems users have had with launching Chunky since the Minecraft Java runtime is a Java 8 runtime.

**Comment by llbit** [comment]
On Windows 7 the Java runtime is in `D:\Program Files (x86)\Minecraft\runtime`. The current Java version used is `1.8.0_25`.

**Comment by leMaik** [comment]
We'll ship our own runtime instead, since Minecraft most likely doesn't ship with JavaFX and retrieving its runtime path on every OS and setup is tricky (just like locating Java is).
