### ISSUE TITLE
How I can use plugin API?

### ISSUE THREAD

**Issue by acterhd** [chunky-dev/chunky#389]
Hello. My previous renderer in Java was fall. But I think try to use JNI in plugin. How to make interopability with custom renderer? 

And by the way, you do not need to plan for the introduction of GPU. I can help...

**Comment by llbit** [comment]
I'm working on documentation for the plugin API. The API is not finished yet, it is a work in progress. The plan is to make a few plugins to decide what the API should look like.

**Comment by empirebuilder1** [comment]
I see that a page has been added to the Chunky website regarding [the Plugin API](http://chunky.llbit.se/plugin_api.html), with some basic details on syntax for said API. However, as the master llbit has already said, it's extremely experimental and could change at any time.

**Comment by acterhd** [comment]
Why you don't want sync project with Mineways?

**Comment by empirebuilder1** [comment]
Because there doesn't seem to be a reason to. Mineways exports mainly .obj files for rendering IIRC - something that would be interesting to have in Chunky, but not really needed.

A future plugin for importing/exporting .obj, .schem and other Minecraft model files might be useful down the road, but for now Chunky's built-in chunk-octree generator works fine.

**Comment by acterhd** [comment]
I also have real-time octree generator, but roughly...

**Comment by acterhd** [comment]
Will possible to load all geometry and material data to custom renderer?

**Comment by llbit** [comment]
@acterhd Yes, that is one goal for the plugin API.

**Comment by leMaik** [comment]
There are a bunch of open source plugins now, which might be a good place to get started. We've also created a small getting started guide here: https://chunky-dev.github.io/docs/plugins/development/
