### ISSUE TITLE
Chunky not Recovering From Sleep

### ISSUE THREAD

**Issue by Consue** [chunky-dev/chunky#408]
It seems like whenever my computer goes to sleep and then later in the day I look over at the progress, chunky seems to be frozen at the last frame it was rendering, Then I looked at my system CPU was idle and my RAM had jumped some 11%.
When I try to pause or show the preview it cant do it and I close the program due to non responsive behavior
This is an issue because now I cant do overnight renders anymore without having my computer on the whole night. Before it would ether finish the render and then go to sleep or simply work on it while asleep, one of those.

**Comment by llbit** [comment]
I have never tested running Chunky while the computer goes to sleep. Chunky should not be able to continue rendering during the sleep, if it really is sleeping and not just blanking the monitor. There might be a bug preventing Chunky from continuing after the computer wakes up again, need to investigate further.
