### ISSUE TITLE
[Bug] Large amount of noise remains in image unless scene is saved and reloaded

### ISSUE THREAD

**Issue by Maxxeine** [chunky-dev/chunky#481]
I've been experiencing this from at least 1.4.2, perhaps before. When I render a scene normally without scene changes, the noise is handled as expected and will decrease as the render progresses. But when I load another scene in the same Chunky session, or make a large change such as adjusting Fog or canvas size, when the scene renders the noise never disappears from the image, no matter how high of an SPP I've rendered to. However, when I start a new Chunky session fresh and load my scene the noise completely disappears.

Below are attached images before/after a session reload, same SPP and render time. Note the drastic decrease in noise upon reloaded scene render.

![hnxcr2e](https://user-images.githubusercontent.com/39843722/40867092-8470ef92-65b6-11e8-82fe-f1f8282ecac8.jpg)
![after](https://user-images.githubusercontent.com/39843722/40867096-8a292d82-65b6-11e8-96ff-133ea135476e.png)

**Comment by jackjt8** [comment]
Just wanted to chime in and confirm this issue. I tend to make heavy use of Load Scene in the Scene controls window and this bug crops up all the time. Likewise I can't confirm the exact version that this became an issue, but It was not present in earlier Chunky builds.

I'll try to download some older Chunky builds to see when it cropped up once I finish up my current batch render.

**Comment by Peregrine05** [comment]
Is this issue still present?

**Comment by jackjt8** [comment]
I do not believe it is. I cannot say I have ran into this issue for a least five years. It's possible it was fixed accidentally. Or it was a bug with JavaFX or something.

As no one else has reported this issue I will close the issue for now; but we can reopen it in the case that someone is able to reproduce it.
