### ISSUE TITLE
[Feature] Water (Wave/Ripple) Animation

### ISSUE THREAD

**Issue by chland** [chunky-dev/chunky#483]
First up a little disclaimer: I did NOT test this properly. So I'm sorry if this is bullshit and i just overlooked something :)

But I did notice this earlier when messing around with some automated animation rendering and saw it again in this Reddit-posting where the water looks like its "frozen in time": https://www.reddit.com/r/chunky/comments/8vbi8l/teaser_of_my_first_animation_project_more_info_in/

If you create an animation the waves/ripples in the water are static. This looks pretty odd if you're rendering some kind of timelapse where (in theory) time should be passing while the camera moves around. 

I don't know how the water ripples are calculated but if they aren't entirely random it might be possible to add some kind of "offset" to change them (similar to the Cloud X/Y/Z offsets or the Height/Azimuth of the sun).

**Comment by llbit** [comment]
Water rendering works by using a precomputed normal map. It would be possible to use a sequence of normal maps to simulate waves.

**Comment by chland** [comment]
I took a quick look at Gerstner Waves, https://github.com/ishmeetkohli/waveAnimation and https://developer.nvidia.com/gpugems/GPUGems/gpugems_ch01.html ... but thats way out of my comfort zone when it comes to math/java and might be total overkill :) 

And I guess animated normal maps would probably be a lot easier.

**Comment by chland** [comment]
I did a quick search: https://blenderartists.org/t/animated-water-normal-map-tileable-looped/673140

Somebody rendered a tileable water-normalmap in Blender (120 frames with 1024 x 1024px -> 117 MB) - probably this could be scaled down and used as a base!?

**Comment by NJDaeger** [comment]
I think the Gerstner waves would be the best option for looks, but for implementation purposes- the animated normal map would be the best option. If that were to be done, I think it would be nice if we could input our own normal map maybe? You could always use the default or set your own or something.

**Comment by chland** [comment]
I just noticed something I never really noticed before (as somehow I never rendered scenes with big oceans). I did some renders with a lot of water and the repeating patterns in it become very obvious. Here is a little example where the patterns can easily be seen: https://imgur.com/XV8ca0K

Probably using a bigger normalmap that gets repeated less frequently could solve this problem?

**Comment by leMaik** [comment]
This feature could also be extended to allow rendering multi-frame textures, like fire.

**Comment by leMaik** [comment]
This was implemented as part of procedural water; i.e. #1082
