### ISSUE TITLE
OpenJFX Issue arising again

### ISSUE THREAD

**Issue by eCyclops** [chunky-dev/chunky#484]
Although I have 
`sudo apt install openjfx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openjfx is already the newest version (8u161-b12-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`
I still get the error `Exception in thread "main" java.lang.NoClassDefFoundError: javafx/stage/Stage` when trying to `java -jar` either chunky or the launcher.

**Comment by andymwat** [comment]
Make sure the version of java you have installed matches the openjfx version. I had the same issue, but was using openjdk-11-jre with the version of openjfx for Java 8. Try uninstalling openjdk-11-jre and installing openjdk-8-jre instead.

**Comment by eCyclops** [comment]
Okay, actually, I changed default jre using `sudo update-alternatives --config java` and then right-clicked on the launcher and chose "Open with OpenJDK Java 8 Runtime" and it worked. Thanks for pointing me in the right direction.
