### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Murdymur** [chunky-dev/chunky#544]
Hey in the window that's meant to show my world, I just have a black screen. Ideas on how to fix?

**Comment by empirebuilder1** [comment]
Chunky currently does not support any Minecraft worlds or textures newer than 1.12 (currently in the works though). You need to create a different world in 1.12 or older to be able to use it with Chunky.

**Comment by EmeraldSnorlax** [comment]
or install the alpha. New blocks will be missing, but it is somewhat functional.
