### ISSUE TITLE
CubicChunks worlds compatibility

### ISSUE THREAD

**Issue by gianniqq** [chunky-dev/chunky#547]
There's this new mod [terra121 ](https://github.com/orangeadam3/terra121)that makes it possible to have a minecraft world that's a 1 to 1 scale of the real world (1 block = 1 meter). It features  terrain, biomes, trees, and roads and is based on data provided by public online datasets.
It's extremely cool and I think that chunky would really give this world a unique perspective. I'd love to be able to make a real life landscape photo and then go to minecraft "Terra" world to the respective area, load enough part of that world and then open it in chunky to make a render of that same landscape.
As of now, I tried to open the world but chunky seems to see only empty regions (pic related):
![immagine](https://user-images.githubusercontent.com/4668449/77341646-511d8100-6d2f-11ea-8a3f-2b30ac0626a7.png)

Minecraft version: 1.12.2 with forge 1.12.2-14.23.5.2838
Mods used:
CubicChunks version 1.12.2-0.1042.0-SNAPAHOT
CubicGen version 1.12.2-0.0.115.0-SNAPSHOT
Let's Encrypt Craft
MalisisCore version 1.12.2-6.5.1-SNAPSHOT
Terra 1 - 1 version 0.1
(I only used the mods required/recommended for the terra121 mod to work)

**Comment by EmeraldSnorlax** [comment]
All that's really needed is cubic chunks mod compatibility, and that would (I assume) be painfully hard to develop around. Also, this issue is better placed on Lemaik's fork, as llbit is on hiatus.

**Comment by gianniqq** [comment]
> All that's really needed is cubic chunks mod compatibility, and that would (I assume) be painfully hard to develop around. Also, this issue is better placed on Lemaik's fork, as llbit is on hiatus.
> 
> https://github.com/leMaik/chunky

I see. I suspected it was mostly a CubicChunks thing, but since I'm no expert in this I'm happy you confirmed it. I submitted a new issue on the Lemaik's fork as you kindly suggested, it can be found [here](https://github.com/leMaik/chunky/issues/11).

**Comment by leMaik** [comment]
This is fixed for <= 1.12 worlds in 2.4.0 by #1031
