### ISSUE TITLE
2.1 Glass reduces intensity of emitters significantly

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#608]
Similar to https://github.com/llbit/chunky/issues/528 but with glass instead. 

1.4.5
![NoiseTest_a_1_water_glass-256](https://user-images.githubusercontent.com/3740917/83980998-ec2afd80-a911-11ea-8a2f-1d8a8cd9ebe4.png)

2.0beta6
![NoiseTest_a_2_water_glass-256](https://user-images.githubusercontent.com/3740917/83980999-edf4c100-a911-11ea-868f-1f951f7e3358.png)

2.1-274
![NoiseTest_a_274_water_glass-256](https://user-images.githubusercontent.com/3740917/83981003-f3520b80-a911-11ea-950f-f951c1faba98.png)

2.1-308
![NoiseTest2_water_glass-256](https://user-images.githubusercontent.com/3740917/83981028-21cfe680-a912-11ea-8461-b96336a20711.png)

**Comment by jackjt8** [comment]
Scene
[scenes.zip](https://github.com/llbit/chunky/files/4743927/scenes.zip)

**Comment by aTom3333** [comment]
![NoiseTest2_water_glass-256](https://user-images.githubusercontent.com/23342398/84033814-be899700-a999-11ea-9000-e598e683893c.png)
I went back to see when that was introduced. It was when `localIntersect` for class was made to be `false`. Setting it back to `true` fixes this issue but we don't get refraction anymore. So i'll have to look further

**Comment by leMaik** [comment]
@aTom3333 We would need to remember that the ray already hit a glass block of that color (`previousMaterial` of the ray) and then skip intersection in the `intersect` method of the glass model. This could make glass blocks behind glass blocks (glass air glass, like in your image) invisible, I'll have to try it out.

Refraction shouldn't be affected by this change. :thinking: It works fine for e.g. slime which also uses local intersection.

**Comment by Stenodyon** [comment]
If `localIntersect` is `true` then the ray goes through the glass instead of generating an intersection that can refract. This is because `TexturedBlockModel.intersect(…)` makes a decision about intersecting the glass block based on the texture alpha but not the refraction index.
https://github.com/llbit/chunky/blob/ed0d57550d6f836690b4ae5ade465f2b7eac42ed/chunky/src/java/se/llbit/chunky/model/TexturedBlockModel.java#L60-L65
Maybe `TexturedBlockModel` should intersect even when the texture alpha is zero and let the path tracer decide what to do based on the texture alpha and refractive index?

**Comment by jackjt8** [comment]
[default_2022-12-05_22-07-25.zip](https://github.com/chunky-dev/chunky/files/10158333/default_2022-12-05_22-07-25.zip)
![image](https://user-images.githubusercontent.com/3740917/205755536-70f48e24-802f-4159-824b-99f1a1601d27.png)

**Comment by JustinTimeCuber** [comment]
From my testing it seems like the effect is most significant when the light source is directly adjacent to the glass.
![image](https://user-images.githubusercontent.com/46458276/206836121-426a7c45-6539-47f5-8f32-2389356f5214.png)
![image](https://user-images.githubusercontent.com/46458276/206836127-3ba4a73f-cc10-4307-b5b4-a4d5151e9796.png)
