### ISSUE TITLE
Finalizing Octree accounts for 2/3rds of load times

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#633]
YouTube video - https://youtu.be/zpafwXZHzTI

Console log - [log2.txt](https://github.com/llbit/chunky/files/4928017/log2.txt)

`Load selected chunks` at 10 seconds

`Finalizing Octree` at 7m10s

`Loaded 70911 chunks` at 19m44s

---

> leMaikToday at 22:11
> TL;DR disk i/o is not the bottleneck, building the octree isn't either but apparently replacing hidden blocks with stone and calculating the shape of lava and water is

> Also, calculating the grass and foliage textures. That could be parallized, though! :thinking:

**Comment by aTom3333** [comment]
@jackjt8 Could you do some new measurement on that issue? I don't think we have measured the impact of #638 on a bigger scale

**Comment by jackjt8** [comment]
Thankfully I have the same map so I can just approximately select the same number of chunks and see where we end up. Tested on 2.2-392; Unfortunately the `Finalizing Octree` message is no longer printed to the console so this makes testing a bit harder.

`Load selected chunks` at 4 seconds

`Finalizing Octree` at 7m39s? --- Just judging it based upon the sudden shift if CPU behaviour from constantly loading a single thread to jumping between multiple threads.

`Loaded 73886 chunks` at 10m4s

Old - 420s, 754s, 1174s
2.2-392 - 455s, 145s, 600s
(loading, finalizing, total)

---

Comparing to my previous results and what you obtained in your own testing on https://github.com/chunky-dev/chunky/pull/638, with a bit of guess work, I am seeing an uptick in Chunk loading times of around +8.3% and a reduction in Finalizing time of -80% (inline with your numbers)*.

`* Assuming that I am guessing the point where Octree Finalization is starting correctly.

**Comment by jackjt8** [comment]
Turns out running Chunky via Headless gives us more information and still has the Octree Finalization completion line written.

To confirm: Pre-https://github.com/chunky-dev/chunky/pull/638: Octree building is 390s, Finalizing 700s.

Post-https://github.com/chunky-dev/chunky/pull/638: Octree building is ~330s, Finalizing is about 130s.

---

There is some variance in my results but there is a clear and marked improvement to this issue.
