### ISSUE TITLE
Underwater surface brightness reduction since #637 (2.2-327 snapshot)

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#645]
before (credits Parson Hogsheade Jr#1879 )
![](https://cdn.discordapp.com/attachments/543090398671929344/735494871896555570/unknown.png)

after (credits Parson Hogsheade Jr#1879 )
![](https://cdn.discordapp.com/attachments/543090398671929344/735495546529120256/unknown.png)

---

Also noticed that the brightness of surfaces appears to be reduced with 327.

2.2-323 - Use the settings when loading a scene with no octree implementation specified (#630)
![2 2 0-323](https://user-images.githubusercontent.com/3740917/88222896-92cb2380-cc5e-11ea-9621-79891f5cdf67.png)

2.2-326 - Fix jello water caused by interaction between water plane and normal water (#635)
![2 2 0-326](https://user-images.githubusercontent.com/3740917/88222912-9b235e80-cc5e-11ea-938b-bab6f736bb45.png)

2.2-327 - Set previous material as water when start is in water and not exiting water (#637)
![2 2 0-327](https://user-images.githubusercontent.com/3740917/88222931-a1193f80-cc5e-11ea-96d8-2488d0f56936.png)

**Comment by leMaik** [comment]
Missing underwater fog has been fixed in #646, reduced surface brightness is still an issue.

**Comment by leMaik** [comment]
I was told that it now looks as expected. 🤷‍♂️
