### ISSUE TITLE
over 50% of chunks do not load in when creating a scene from selected chunks

### ISSUE THREAD

**Issue by UAVwaffle** [chunky-dev/chunky#651]
My prev. issue was closed because someone said it was fixed.  It was not fixed in the latest snapshot and the issue seems to have gotten worse (even less chunks show up) I will now paste in what I said last time and link to the prev. issue allong with post a few more updated photos
  

https://github.com/llbit/chunky/issues/648

The attached screenshots show the issue.

When I first installed everything worked fine, then the next day I decide to make a even bigger render, that's when I first expirenced this bug. Now it does not matter how much ram is allocated it does this and I can only make small renders (much smaller than what I could do before) lastly when I try to make a new scene after it does this I get a error window that says, " warning, can't load chunks right now" I get this box whenever I make a new scene until I restart the software. I tried deleting and reinstalling chunky and even tried different versions (latest normal and latest snapshot) they both do this.

![Screenshot (409)](https://user-images.githubusercontent.com/68166007/88487195-f8662b00-cf50-11ea-9b13-c20b6ef6b6d0.png)
![Screenshot (408)](https://user-images.githubusercontent.com/68166007/88487197-f8662b00-cf50-11ea-80cf-a7517579c14d.png)
![Screenshot (407)](https://user-images.githubusercontent.com/68166007/88487198-f8fec180-cf50-11ea-84bc-09499beb4f69.png)
![Screenshot (406)](https://user-images.githubusercontent.com/68166007/88487199-f8fec180-cf50-11ea-8c16-463f9b933743.png)
![Screenshot (405)](https://user-images.githubusercontent.com/68166007/88487200-f9975800-cf50-11ea-8bf4-a97a4a5b0efb.png)

**Comment by DeltaTerrainz** [comment]
How much RAM do you have? I can see that you're trying to load ~87k chunks.

**Comment by UAVwaffle** [comment]
someone asked, "Is this by any chance a world that was converted to 1.14 after being downloaded with WorldDownloader?"
the answer is no the world was created in 1.16.1 and the version was never changed

**Comment by DeltaTerrainz** [comment]
yea, but how much system RAM do you have?

**Comment by UAVwaffle** [comment]
@DeltaTerrainz changing the amount of ram does not increase or decrease the threashold of this glitch (my prev. comment was for someone else)  I have changed the amount of ram allocated from 1gb - 10gb (10gb is the most I can give to this proccess I have 16gb installed on my pc) as stated in my prev. issue the threshold seems changes each time, but I forgot to mention I noticed that it seems to start between 35-60k chunks.  also I know it's not a ram issue because I did a render with 40-50k chunks twice, but I stopped it because I wanted to select a different area and now I can't even come close to the size render. also the issue has gotten worse since the last update, before only 50% chunks showed up and now about 25% The top photo is the most recent one the bottom is the oldest, if you look at the newer one even less chunks show up

**Comment by DeltaTerrainz** [comment]
Yeah, 16GB starts struggling to load any world that exceeds ~60k chunks I believe. Chunky simply refuses to load any more because there is no RAM to load it to. Your issue is too large of a selection.

**Comment by leMaik** [comment]
@UAVwaffle That "someone" was me and I actually expected the fix to fix your issue.

It's very weird that the amount of chunks you can load suddenly changes. The last update shouldn't cause _less_ chunks to be loaded because we now actually _ignore_ some chunk errors so that _more_ chunks should be loaded. Are you able to play normally in the world in Minecraft?

**Comment by jackjt8** [comment]
The world you have load is called **world**; this is typically the name given to server maps. Would you please let us know if this is a server map and if so what server .jar are you using?

**Comment by leMaik** [comment]
> when I try to make a new scene after it does this I get a error window that says, " warning, can't load chunks right now" I get this box whenever I make a new scene until I restart the software

:thinking: Could you zip that world and send it to us?

**Comment by UAVwaffle** [comment]
k so I need to answer a few questions...
@jackjt8 Yes it is a server, I hosted it on my pc using spigot then later switched to paper when uploading it to apex hosting.  @leMaik for your first question...  the world plays fine when loaded onto singleplayer 1.16.1 and my server is running perfectly.  on were you said it shouldn't load less chunks, Yes I agree this is very strange I will supply a screenshot of a higher vantage point so you can see all the missing chunks.  and to the final question I will also provide a .zip file of the exact copy I was using.  inside of the world folder you will see 4 files use the one that's titled "world" UPDATE:  actually the zip file will take a bit longer because I need to upload the file else were (I think I'll have to make my own github thing idk I am new to github)



![Screenshot (413)](https://user-images.githubusercontent.com/68166007/88487609-c3f46e00-cf54-11ea-864c-c29daf8b7e66.png)

**Comment by UAVwaffle** [comment]
so right now the file is uploading (I'm trying to use google drive) I was wondering if there is a way to view debug logs (It might speed up the process)    Also thanks for the help

**Comment by UAVwaffle** [comment]
Alright this is the world download:    https://drive.google.com/file/d/18qi3nRGUO92tvhDHf64uCjVpkUHctGoD/view?usp=sharing

**Comment by UAVwaffle** [comment]
Do you want the files I'm using for chunky maybe you could re-produce the problem them

**Comment by UAVwaffle** [comment]
Here's the chunky file I'm using.  this is the files used for the most recent render attempt(top and last photo) https://drive.google.com/file/d/18qi3nRGUO92tvhDHf64uCjVpkUHctGoD/view?usp=sharing

**Comment by leMaik** [comment]
The following build could fix the issue. Unzip the zip file and launch the jar. It will open the launcher, just launch the "latest" version with it (ignore the 1.4.5 version in the window title, it's just a local snapshot and the version isn't set properly).

[chunky-1.4.5-346-g1a50809d.zip](https://github.com/llbit/chunky/files/4978387/chunky-1.4.5-346-g1a50809d.zip)

**Comment by UAVwaffle** [comment]
same issue, but did some test while STARING at task manager and this is what I found:   when rendering 80k chunks with 1gb ram I get a ton of missing chunks, with 80k chunks and 7,600 mb of ram It loads  until it reaches 7,600mb of ram usage then stops and it has 50% missing chunks,  with 24k chunks 7,600 mb of ram allocated it loads until it reaches 5,400 - 5,600 mb of ram then it stops and has messing chunks, but less.   when rendering with 14,745 chunks (same ram) it reaches the same cap as prev. but everything works correctly (no missing chunks).  every time it loads incorrectly if I try to load a new scene it says "can't load chunks right now".    1 of 3 things seem to be happening:  1: after a certain limit of chunks is reached it stops loading chunks and just splits the chunks cap between random chunks(I did not set a chunk cap, chunk cap is just used for this example).   2: after a certain amount of ram is used the process crashes and I get a incomplete scene.  3: both combined.   any further replies will be delayed because I have to go to a party (it's my sisters b-day).               just incase I used your file wrong heres what I did:   I ran the .jar file selected it to install in the current directory, then when the launcher opened I just clicked launch without pressing any other buttons, finally, I selected my world and chunks and started

**Comment by leMaik** [comment]
> Yeah, 16GB starts struggling to load any world that exceeds ~60k chunks I believe. Chunky simply refuses to load any more because there is no RAM to load it to. Your issue is too large of a selection.

@UAVwaffle you are trying to load too many chunks without enough ram, as already mentioned. As you can see, if there is enough ram, loading works fine.

**Comment by UAVwaffle** [comment]
but that's the thing, when I do a render of 25k it stays 2,000mb bellow the ram cap and it still doesn't work, is it possible to view a debug log to see exactly whats happening?  the only time it stops at the ram cap is when I do a 80k one

**Comment by UAVwaffle** [comment]
but if you still believe it to be a ram issue, how much would you recommend for massive 80-120k renders?

**Comment by ProNoob135** [comment]
generally i open task manager and watch how much chunky uses, if it uses all of it then you're loading too many

**Comment by jackjt8** [comment]
An approximation for 80k chunks you would need to allocate at least 16GiB and for 120k chunks it would be a minimum of 24GiB assuming natural vanilla world generation with no player made objects. Complex chunks, being those: from amplified worlds, with signs, armour stands, etc., will require more memory and I would figure that ~24GiB for 80k chunks is nothing unusual.

The world loading process creates objects in memory that do not get collected by JVM's GC that quickly. Typically, once you reach ~80% usage the GC will kick in a bit more and it will clean up some of these objects. It's one of the reasons why the last ~20% of your memory can appear to fit so many chunks compared to the first 80%. There isn't much we can do about that behaviour it's just something you need to learn.

**Comment by leMaik** [comment]
>is it possible to view a debug log to see exactly whats happening? the only time it stops at the ram cap is when I do a 80k one

@UAVwaffle The easiest way would be starting chunky from command line, which will give you some debug output there. You'll see that it raises exceptions during chunk loading.

The weird thing is that I was able to reproduce your bug from above (Null Pointer Exception while chunk loading, thus it wasn't possible to load more chunks later and I had missing chunks and got the same warning message as you until I restarted chunky) but my fix fixed it for me. 🤔

**Comment by UAVwaffle** [comment]
@leMaik sure thing!  I'll try to get it tomorrow.  (if my recording software will let me I'll try and record a video so you can basically see my steps, but i don't think I could run both programs at the same time so i'll have to end the recording before I start and start it up afterwards)   I do have 1 question,  do you want the screenshots of a 25k failed render, a massive 80k failed render or both?

**Comment by UAVwaffle** [comment]
I'm getting the screenshots now, but before I send them I noticed this:   on my copy that wasn't working the 2d map would load a little bit, but would never finish loading, but on your fixed version you sent me the 2d map finishes loading, soooo... atleast the 2d map works,  I'll have to photos in a few minutes

**Comment by UAVwaffle** [comment]
here are the screenshots.  I did 2 renders, first around 85k the second around 23k.  On the 85k ram capped out then it stopped, on 23k ram never went above 5,600mb.  I have around 7,500mb of ram and I could probs allocate 10gb, but left it at 7.5 for consistancy.

![Screenshot (418)](https://user-images.githubusercontent.com/68166007/88572936-ff9f3e80-d00d-11ea-9909-96741dfc3ea8.png)

![Screenshot (425)](https://user-images.githubusercontent.com/68166007/88572924-fd3ce480-d00d-11ea-9de7-e3b3532dfb96.png)
![Screenshot (424)](https://user-images.githubusercontent.com/68166007/88572927-fdd57b00-d00d-11ea-9a60-4fb455318308.png)
![Screenshot (423)](https://user-images.githubusercontent.com/68166007/88572928-fe6e1180-d00d-11ea-80bd-56fc00e47f9e.png)
![Screenshot (422)](https://user-images.githubusercontent.com/68166007/88572929-fe6e1180-d00d-11ea-8eef-8637750f0d75.png)
![Screenshot (421)](https://user-images.githubusercontent.com/68166007/88572930-fe6e1180-d00d-11ea-82d7-ce840da9084b.png)
![Screenshot (420)](https://user-images.githubusercontent.com/68166007/88572932-ff06a800-d00d-11ea-8044-ba8edb67a006.png)
![Screenshot (419)](https://user-images.githubusercontent.com/68166007/88572933-ff06a800-d00d-11ea-80e6-861a22df0348.png)

**Comment by UAVwaffle** [comment]
p.s. the screenshots with more missing chunks is the 85k render

**Comment by UAVwaffle** [comment]
the only setting changed was the canvas size.

**Comment by leMaik** [comment]
@UAVwaffle You can also edit comments instead of creating one comment per sentence. 😉 Makes this easier to follow and produces less noise in our Discord.

**Comment by UAVwaffle** [comment]
@leMaik is there anything else you might need from me,  I'm going to be away for the next couple of days and won't be able to access my pc

**Comment by leMaik** [comment]
@UAVwaffle Not for now. I'll look into this again when I have time. 👍

**Comment by UAVwaffle** [comment]
Alright so as a experiment I copied your "fixed" file to a different folder, then I launched it, but I updated it to the most recent snapshot.  After doing that everything, but the external map seems to be working.   So this is the rundown, I can make a render as long as I keep it below around 26k chunks, which seems normal because any more and it tries to use more ram than I can give it.  The only issue is the 2d map does not load correctly.  The grey part loads correctly, but after a few seconds it just stops loading the regular map.  This is not a issue for me, but if you want to try to fix or want me to make a different issue on the subject tell me.   I do not know if the update would work on the other broken chunky files, I don't have time to test it right now.  I will now attach the screenshot of it and the complete render (rendered at 1,000) this time I have around 9.7gb of ram allocated


![default_2020-07-27_15-53-49-1000](https://user-images.githubusercontent.com/68166007/88603659-8d495100-d043-11ea-8055-9b7f35b05c12.png)


![Screenshot (428)](https://user-images.githubusercontent.com/68166007/88603638-7acf1780-d043-11ea-9d79-e57ed61d5a63.png)
![Screenshot (427)](https://user-images.githubusercontent.com/68166007/88603640-7b67ae00-d043-11ea-990a-d740dec1c1ac.png)

**Comment by leMaik** [comment]
@UAVwaffle Indeed, there are a few chunks that we can't load and currently, the map loader crashes if that's the case. Looks like I didn't commit the change that fixes this (I had that on my disk). PR incoming, your map then renders pretty much fine:

![image](https://user-images.githubusercontent.com/5544859/89071262-9ce3d500-d376-11ea-9a36-03962bdba36a.png)

**Comment by leMaik** [comment]
@UAVwaffle Please ping me if this still isn't fixed :sweat:

**Comment by UAVwaffle** [comment]
@leMaik Everything is now working perfectly.  Thank you so much for your help and this amazing program! 😄
