### ISSUE TITLE
Show Guides on Render Preview missing + Additional guides

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#653]
An option missing from Chunky 2.X is the `Show Guides` right click option with the Render Preview.

![image](https://user-images.githubusercontent.com/3740917/88657596-14d9a300-d0ca-11ea-88b8-eb50dfe518fe.png)

![image](https://user-images.githubusercontent.com/3740917/88657663-333f9e80-d0ca-11ea-91d1-9e47cfa3c4b1.png)

---

While eyeballing is an option, having guides is a big help when framing up shots. Additional guides could also prove useful.

Additional guides:
- Golden Ratio - **Might add via a plugin**
- ~~Rule of Quarters~~
- ~~Diagonals?~~

**Comment by leMaik** [comment]
:100: This would be so cool!

**Comment by jackjt8** [comment]
Additional guides (may) be added via a plugin.
