### ISSUE TITLE
Theres a lot of noise and none of my world gets loaded in render preview

### ISSUE THREAD

**Issue by AbbyDabby246** [chunky-dev/chunky#658]
![image](https://user-images.githubusercontent.com/54068324/88951328-727d1380-d2b3-11ea-8bbe-c6521b32139c.png)
This is what its showing
have no idea what to do
mc version 1.16.1

**Comment by jackjt8** [comment]
Make a selection under the `Map` tab.

Then either:
- Scene > Load selected chunks
- Right click on map > New scene from selection

**Comment by AbbyDabby246** [comment]
> Make a selection under the `Map` tab.
> 
> Then either:
> 
> * Scene > Load selected chunks
> * Right click on map > New scene from selection

Thanks
This worked
