### ISSUE TITLE
Corrupted chunks in 1.16.1

### ISSUE THREAD

**Issue by Rundik** [chunky-dev/chunky#664]
As you can see here, it's not displayed correctly. Tried the latest version and the beta 2.0
![world-146](https://user-images.githubusercontent.com/13032812/89107572-4340e080-d432-11ea-9c65-1271d00ca071.png)

**Comment by jackjt8** [comment]
[The latest version of Chunky is 2.2. Please update to this version for full support of Minecraft 1.13+ worlds](https://chunky.lemaik.de/installation). 2.0beta6 is outdated.

How did you manage to find the download link to 2.0? I would assume it was via https://chunky.llbit.se/?

**Comment by Rundik** [comment]
> [The latest version of Chunky is 2.2. Please update to this version for full support of Minecraft 1.13+ worlds](https://chunky.lemaik.de/installation). 2.0beta6 is outdated.
> 
> How did you manage to find the download link to 2.0? I would assume it was via https://chunky.llbit.se/?

I used http://chunkyupdate2.llbit.se as suggested here https://chunky.llbit.se/chunky2.html
It was the top google result btw

**Comment by jackjt8** [comment]
Ah, I am working on trying to get that paged modified. The homepage already has a direct link to Chunky 2.2 but not that one. Should be resolved soon. Thank you for confirmation of that.

Otherwise follow the new link to Chunky 2.2.

**Comment by Rundik** [comment]
It works with the new version, I checked. I'm gonna close the issue then

**Comment by leMaik** [comment]
@Rundik The docs are updated now to avoid future confusion. Glad you got Chunky working! 👍
