### ISSUE TITLE
Error - Could Not get skull texture

### ISSUE THREAD

**Issue by AlcoRS11** [chunky-dev/chunky#680]
Whenever I launch chunky to render something, I am flooded with an insane amount of errors in regards to skull textures. If its a large render, it'll lock up my computer until I forcibly terminate chunky due to the sheer amount of error windows it produces (can be over 700 of them) When I render structures without skulls, I do not get the error and chunky works as expected.
See the attached image for the error.
![image](https://user-images.githubusercontent.com/11202393/91003668-f0c19280-e59f-11ea-9560-7aa0d2365e5d.png)

**Comment by leMaik** [comment]
@AlcoRS11 Could you send us the regions that contain the chunks with the skulls that cause this error? That way I can try to reproduce this issue.

**Comment by AlcoRS11** [comment]
[ALCO_RS11-Region-r.0.0.zip](https://github.com/chunky-dev/chunky/files/5125861/ALCO_RS11-Region-r.0.0.zip)
The region file is contained in the zip.

**Comment by leMaik** [comment]
@AlcoRS11 Thank you. I now know what causes this bug and will fix it tomorrow (the proper fix would be adding a non-strict mode [to the JSON parser](https://github.com/llbit/jo-json), I'll see if I can prepare a PR for it).

**Comment by AlcoRS11** [comment]
Ok, thanks

**Comment by leMaik** [comment]
This is broken again (or my fix was invalid).
