### ISSUE TITLE
Problems launching

### ISSUE THREAD

**Issue by Enegmatic** [chunky-dev/chunky#682]
Hi. i recently found out about chunky and wanted to render some things for something I'm working on.
I downloaded the latest version and tried to run it but absolutely nothing shows up.  No .chunky folder is made, no installation screen, etc.  I deleted the program and installed the recommended version of java before downloading chunky again, with still no success.
what can I do to fix this?

**Comment by leMaik** [comment]
Which version of Java are you using, which version of the Chunky launcher did you use?

**Comment by PiSaucer** [comment]
I also have this problem

**Comment by leMaik** [comment]
Without any information about your system, java installation or what error you get, I'm afraid we can't help you. You may want to join our Discord, where the community usually figures out such problems in a matter of hours. :-)
