### ISSUE TITLE
Strange burn ins when using new Emitter Strategy Settings

### ISSUE THREAD

**Issue by Lohfrum-Faleign** [chunky-dev/chunky#692]
Setting Emitter Sampling Strategy to ALL causes unusual burn ins at low Emitter Intensity settings. I will included a zip of a test scene where the burn in is especially noticeable. It also happens when Sampling Strategy is set to ONE, but not as heavily. Image provided was set to Emitter Strength 1, Sampling Strategy ALL, and Target SPP of 16. The upper image is the raw png, the lower is the denoised result.
[EmitterSamplingStrategyTut.zip](https://github.com/chunky-dev/chunky/files/5300789/EmitterSamplingStrategyTut.zip)
![ESS-ALL-16-EI-1](https://user-images.githubusercontent.com/49575771/94594356-80b9c280-0257-11eb-8fb4-a420a2499268.png)

**Comment by Peregrine05** [comment]
This was fixed in #1109.

**ESS: All:**
![ess_all_2 5 0](https://user-images.githubusercontent.com/92183530/181904920-57293e16-1ff0-42a2-90b9-c66b9e50608f.png)
