### ISSUE TITLE
bug? dont know for sure

### ISSUE THREAD

**Issue by Leikonka** [chunky-dev/chunky#694]
hello,
   I tried to render picture from 1.16.3 minecraft in chunky launcher, I did some pictures from 1.15 version in it before, so i know it worked, but this picture is completly messy, dont know what to do, in original world is everythink alright, but when I try to render, it is without format and buildings are bombed to unknown.. the world downloaded via world downloader, before I did the same thing, and is was normal without problem
![2020-10-01_19 29 25](https://user-images.githubusercontent.com/51082150/94845657-494a4200-0420-11eb-8bcf-44320b0887c5.png)
![default-40](https://user-images.githubusercontent.com/51082150/94845659-49e2d880-0420-11eb-917e-53fee7fbfa7a.png)

**Comment by jackjt8** [comment]
1.16 made a few changes to how worlds are stored. You need to update to at least Chunky 2.2 for full 1.16 support; or the snapshots which have additional features.

**Comment by Leikonka** [comment]
Thanks! Solved
