### ISSUE TITLE
Chunky 2 Installer?

### ISSUE THREAD

**Issue by bc-185** [chunky-dev/chunky#700]
Chunky 2 should have an installer like Chunky 1.4.5. However, Minecraft comes with a bundled JRE, so installing Java is not required. However, the process of using that to run Chunky is a bit tricky, although I managed to do it on my Windows PC. This should be done to the Windows Installer. Since the runtime is in a folder called `jre-x64` on Windows 64 bit and `jre-x86` on Windows 32 bit. When the exe file is clicked, it will try to find and invoke Minecraft's Java. There is also a chunky.bat file that launches Chunky. Jason Fitzpatrick wrote in an article about the Minecraft Launcher that has a bundled Java "If Minecraft is the only reason you have Java installed, you now have no reason to open up your system to Java vulnerabilities." Should you ever want to do this to the Chunky 1.4.5 installer, Launch4j or shortcuts with the right command can be used to do this.

64 bit:

[Chunky2-win64.zip](https://github.com/chunky-dev/chunky/files/5330602/Chunky2-win64.zip)

32 bit:

[Chunky2-win32.zip](https://github.com/chunky-dev/chunky/files/5330604/Chunky2-win32.zip)

**Comment by leMaik** [comment]
Thanks a lot for looking into this! :+1: 

I'll close this as a duplicate of #526, we'll publish and installer of the launcher soon (using jlink/jpackage), see https://github.com/chunky-dev/chunky/issues/526#issuecomment-855473959
