### ISSUE TITLE
Skulls worn/held by armorstands

### ISSUE THREAD

**Issue by RocketNinja15** [chunky-dev/chunky#727]
Hello! 

Skulls are not rendering, they show up with a popup saying that it cant be loaded

Chunky 2

**Comment by leMaik** [comment]
Which version of chunky are you using? 2 is too unspecific. What does the popup say?

**Comment by RocketNinja15** [comment]
2.3.0 It says failed to load minecraft:skull

**Comment by leMaik** [comment]
Oh, that's because Chunky can't render items (except armor) yet that are held by armorstands. See #669 

Since skulls are already implemented as blocks, letting armorstands wear them might not be much work.

**Comment by leMaik** [comment]
@RocketNinja15 This will be fixed in the next snapshot
