### ISSUE TITLE
Pre-directory scenes with emittergrids/dumps are not copied over to new directory upon scene rename

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky#742]
Upon loading a pre-directory scene (ie a scene that exists within `\scenes\` rather than `\scenes\<scenename>\`) and renaming the scene a new scene directory is created with the new name. Expected behaviour observed with new scheme scenes is that a scenes dump, emittergrid (if exists), json, and octree2 are copied from `\scenes\scene1\` to `\scenes\scene2\`.

With old scheme scenes, only the json and octree2 are copied from `\scenes\` to `\scenes\scene2`. The emittergrid and dump do not get copied automatically.

A simple fix is to save the scene after it has been renamed but this can waste considerable time depending on the scene size.

**Comment by jackjt8** [comment]
Confirmed this issue exists on Chunky 2.4-191-g248ad897; Only .json and .octree2 get copied to the new directory.

**Comment by leMaik** [comment]
This would be pretty hard to fix and the workaround sounds good to me. :upside_down_face:
