### ISSUE TITLE
Render is only water on my map?

### ISSUE THREAD

**Issue by RudolfFink** [chunky-dev/chunky#770]
Hello, the program renders my map on my players location in a city. the whole world is just ocean, or just black screen?

**Comment by leMaik** [comment]
You are most likely using the wrong Chunky version for your Minecraft version. For Minecraft 1.13 or later, use Chunky 2.3, which you can get here: https://chunky.lemaik.de/installation

**Comment by RudolfFink** [comment]
> You are most likely using the wrong Chunky version for your Minecraft version. For Minecraft 1.13 or later, use Chunky 2.3, which you can get here: https://chunky.lemaik.de/installation

I am using version 1.4.5 and playing on 1.16.4

**Comment by RudolfFink** [comment]
> You are most likely using the wrong Chunky version for your Minecraft version. For Minecraft 1.13 or later, use Chunky 2.3, which you can get here: https://chunky.lemaik.de/installation

It works after update hell yeeah!
