### ISSUE TITLE
Dump merging still uses old dump format

### ISSUE THREAD

**Issue by ShirleyNekoDev** [chunky-dev/chunky#783]
The dump format in `saveDump(RenderContext context, TaskTracker progress)` was updated in #756 (with fallback while loading),
but the code in `mergeDump(File dumpFile, TaskTracker taskTracker)`  can only load the old format.

**Comment by ShirleyNekoDev** [comment]
I'll volunteer to fix this with a rewrite of the dump code into its own class. (I cannot assign myself)

**Comment by ShirleyNekoDev** [comment]
I believe another issue is that the new format code in `tryLoadDump(RenderContext context, String fileName, TaskTracker taskTracker)` forgot to `finalizePixel(x, y)` each pixel.
I'll introduce a method for finalizing the whole buffer.

**Comment by aTom3333** [comment]
This method already exists and is called after loading the whole dump https://github.com/chunky-dev/chunky/blob/309950f8b56315fbc4aad1ed3a37c467438ba9e1/chunky/src/java/se/llbit/chunky/renderer/scene/Scene.java#L508
So if think the individual calls to `finalizePixel` when loading an old dump are unnecessary.
