### ISSUE TITLE
Building version 2 throws errors 

### ISSUE THREAD

**Issue by Davilarek** [chunky-dev/chunky#787]
I have latest JRE and JDK installed but gradlew.bat throws tons of errors. 

I've put all the errors in file 

[log.txt](https://github.com/chunky-dev/chunky/files/5836087/log.txt)

Probably I'm just dumb and can't get it to work

**Comment by leMaik** [comment]
Looks like JavaFX SDK is missing. We need to update the readme to include the necessary steps.

**Comment by jackjt8** [comment]
Which latest JDK? Chunky's gradle script works for JDK8 however for JDK11+ you need to patch it for it to find JFX. 

[a_Tom made a .patch file that'll update all the gradle scripts](https://jackjt8.github.io/ChunkyGuide/assets/downloads/jdk11-jfxpatch.patch)

Couldn't we just check if the 'java_version[0] >= 11' and then run the patched commands? I think it's just one or two lines per script which get patched using the .patch.

**Comment by leMaik** [comment]
@jackjt8 As far as I'm concerned we could also update to JDK11, make use of `Math.fma` and other goodies and use JFX as a gradle dependency.

**Comment by leMaik** [comment]
Would something like this work? (based on @aTom3333's patch):

```diff
Index: build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- build.gradle	(revision 221bc3f91415b73bb5eb33f21d3379376c3f467d)
+++ build.gradle	(date 1590599024452)
@@ -1,3 +1,12 @@
+if (JavaVersion.current().isJava11Compatible()) {
+  plugins {
+    id 'org.openjfx.javafxplugin' version '0.0.8'
+  }
+  
+  javafx {
+    version = "11"
+    modules = ['javafx.controls', 'javafx.fxml']
+  }
+}
+
 project.version = getVersion()
 
 println "Building version ${project.version}"
Index: lib/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/build.gradle	(revision 221bc3f91415b73bb5eb33f21d3379376c3f467d)
+++ lib/build.gradle	(date 1590599024452)
@@ -1,3 +1,12 @@
+if (JavaVersion.current().isJava11Compatible()) {
+  plugins {
+    id 'org.openjfx.javafxplugin' version '0.0.8'
+  }
+  
+  javafx {
+    version = "11"
+    modules = ['javafx.controls', 'javafx.fxml']
+  }
+}
+
 sourceSets.main.java {
   srcDir 'src'
 }
Index: launcher/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- launcher/build.gradle	(revision 221bc3f91415b73bb5eb33f21d3379376c3f467d)
+++ launcher/build.gradle	(date 1590599024452)
@@ -1,3 +1,12 @@
+if (JavaVersion.current().isJava11Compatible()) {
+  plugins {
+    id 'org.openjfx.javafxplugin' version '0.0.8'
+  }
+  
+  javafx {
+    version = "11"
+    modules = ['javafx.controls', 'javafx.fxml']
+  }
+}
+
 dependencies {
   compile project(':lib')
 }
Index: chunky/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- chunky/build.gradle	(revision 221bc3f91415b73bb5eb33f21d3379376c3f467d)
+++ chunky/build.gradle	(date 1590599024452)
@@ -1,3 +1,12 @@
+if (JavaVersion.current().isJava11Compatible()) {
+  plugins {
+    id 'org.openjfx.javafxplugin' version '0.0.8'
+  }
+  
+  javafx {
+    version = "11"
+    modules = ['javafx.controls', 'javafx.fxml']
+  }
+}
+
 apply plugin: 'application'
 apply plugin: 'maven'
 apply plugin: 'signing'
```

**Comment by aTom3333** [comment]
The version of the plugin should only in the root file, other than that I feel like this should work

**Comment by leMaik** [comment]
Whoops, copy/paste error… I'll update the patch

**Comment by leMaik** [comment]
@Davilarek Were you able to build Chunky with the patch provided above?

**Comment by Davilarek** [comment]
sorry for no response, I just want use chunky, it's my first contact with it, I've never build it before, I even don't know how to use the patch

**Comment by leMaik** [comment]
Then the installation page at https://chunky.lemaik.de/installation will probably help you. :+1: We provide pre-build jar files of everything (including snapshots that are built every night).
