### ISSUE TITLE
Black bars & colored pixels in sky

### ISSUE THREAD

**Issue by StanleyMines** [chunky-dev/chunky#825]
In both preview and in render, black bars and boxes appear in the sky. Seems to only apply for SPP 1, and becomes normal after that, so high SPP normalizes it out to the correct sky color. Also seems to depend greatly on canvas size. This is happening on both Preetham as well as Nishita.

Example on Preetham in both preview and rendered:

![Screenshot 2021-02-20 at 07 19 48_5](https://user-images.githubusercontent.com/4878558/108600767-db120780-734d-11eb-8f47-307df7b7c138.gif)

This might have to do with the sky stuff that @alexhliu has been working on.

Tested on commit 209fd07.

**Comment by jackjt8** [comment]
Just wanted to chime in and confirm this issue. 

This is a 2 SPP render where you can see the black bars are baked into the final image.
![image](https://user-images.githubusercontent.com/3740917/108600958-e5ee8b80-7391-11eb-9eed-0880a50de94c.png)
