### ISSUE TITLE
Clicking on the render start, pause, and stop buttons while chunks are loading causes a freeze.

### ISSUE THREAD

**Issue by alexhliu** [chunky-dev/chunky#832]
Clicking on these buttons (and probably more) will cause Chunky to lockup until the chunks are finished loading. This is likely due to the fact that these button's callbacks all call `Scene` synchronized methods.

**Comment by leMaik** [comment]
Should we disable the buttons while loading chunks? Why would you do that anyway

**Comment by NJDaeger** [comment]
> Should we disable the buttons while loading chunks? Why would you do that anyway

I think it makes sense to disable the start button, but is it possible the pause and stop buttons could be used to pause or stop the chunk loading?
