### ISSUE TITLE
Octree re-saves after every save

### ISSUE THREAD

**Issue by TheRealJayjayli** [chunky-dev/chunky#844]
When hitting save, Chunky will re-save the octree, even if it hasn't been modified:
```
Saving scene Greenfield360-2
Saving octree Greenfield360-2.octree2
Octree saved
Saving render dump: C:\Users\jayjayli\.chunky\scenes\Greenfield360-2\Greenfield360-2.dump
Render dump saved: C:\Users\jayjayli\.chunky\scenes\Greenfield360-2\Greenfield360-2.dump
Scene saved
```

I can confirm this happnes with automatic dump saving too.

This issues occur on `Chunky 2.4.0-91-g5eaee6fa`

Previous versions of Chunky skipped the redundant octree write.

**Comment by leMaik** [comment]
I can't reproduce this.

```
Saving scene 0-21w10a
Saving octree 0-21w10a.octree2
Octree saved
Saving render dump: /home/maik/.chunky/scenes/0-21w10a/0-21w10a.dump
Render dump saved: /home/maik/.chunky/scenes/0-21w10a/0-21w10a.dump
Scene saved
Saving scene 0-21w10a
Skipping redundant Octree write
Saving render dump: /home/maik/.chunky/scenes/0-21w10a/0-21w10a.dump
Render dump saved: /home/maik/.chunky/scenes/0-21w10a/0-21w10a.dump
Scene saved
Saving scene 0-21w10a
Skipping redundant Octree write
Saving render dump: /home/maik/.chunky/scenes/0-21w10a/0-21w10a.dump
Render dump saved: /home/maik/.chunky/scenes/0-21w10a/0-21w10a.dump
Scene saved
```

**Comment by jackjt8** [comment]
```
Octree loaded
Saving scene ess_test
Skipping redundant Octree write
Saving render dump: D:\Programs\Chunky_293\scenes\ess_test\ess_test.dump
Render dump saved: D:\Programs\Chunky_293\scenes\ess_test\ess_test.dump
Saving Grid ess_test.emittergrid
Scene saved
```

Could you prune the number of chunks, confirm if the issue occurs, and then upload the scene?

**Comment by TheRealJayjayli** [comment]
With 1024 chunks, the issue is still there:
```
Loaded 1024 chunks
Building new octree (DICTIONARY)
Building new octree (DICTIONARY)
Saving scene default_2021-03-13_10-46-40
Saving octree default_2021-03-13_10-46-40.octree2
Octree saved
Saving render dump: C:\Users\jayjayli\.chunky\scenes\default_2021-03-13_10-46-40\default_2021-03-13_10-46-40.dump
Render dump saved: C:\Users\jayjayli\.chunky\scenes\default_2021-03-13_10-46-40\default_2021-03-13_10-46-40.dump
Scene saved
Saving scene default_2021-03-13_10-46-40
Saving octree default_2021-03-13_10-46-40.octree2
Octree saved
Saving render dump: C:\Users\jayjayli\.chunky\scenes\default_2021-03-13_10-46-40\default_2021-03-13_10-46-40.dump
Render dump saved: C:\Users\jayjayli\.chunky\scenes\default_2021-03-13_10-46-40\default_2021-03-13_10-46-40.dump
Scene saved
```

This was on the latest snapshot as of today - the scene is attached below:

It also seems to occur again, even with one chunk selected.
The scene with 1 chunk is also attatched below.
[default_2021-03-13_10-49-20.zip](https://github.com/chunky-dev/chunky/files/6134610/default_2021-03-13_10-49-20.zip)
[1chunk.zip](https://github.com/chunky-dev/chunky/files/6134611/1chunk.zip)

**Comment by leMaik** [comment]
Chunky just checks the file modification time and re-saves the chunk if it has changed since the last time it was saved. :thinking:

**Comment by TheRealJayjayli** [comment]
Is there anything you need me to do?

**Comment by TheRealJayjayli** [comment]
It turns out this the octree seems to only save twice on the first attempt for the scene. If a new scene is created, and it is saved, and saved again (without restarting Chunky), the octree saves twice. However, if you save the scene and restart Chunky (or open any existing save), it will skip the octree write.
