### ISSUE TITLE
Water plane not below y < 1 (MC 1.17)

### ISSUE THREAD

**Issue by ShirleyNekoDev** [chunky-dev/chunky#854]
Y min clip can already handle Minecraft 1.17 y down to -64, but water planes are impossible for y < 1.
I found the following relevant code which would need to be updated:
 - for the GUI: `WaterTab>>update (line 82, 85)`, `WaterTab>>initialize (line 122)`
 - for the ray tracing: `PreviewRayTracer>>nextIntersection (line 95)`, `Scene>>isInWater (line 2382)`,

**Comment by leMaik** [comment]
If you want, you could update these lines 😁
