### ISSUE TITLE
Launcher uses invalid module-path syntax and fails to start

### ISSUE THREAD

**Issue by zocker-160** [chunky-dev/chunky#856]
It looks like the default settings for the `java options` is `--module-path \"/usr/share/openjfx/lib\"`, but the escaped quotation marks seem to be invalid syntax, because with that I get `java.lang.module.FindException: Module javafx.controls not found`.

When I remove the `\"` and use `--module-path /usr/share/openjfx/lib` instead it works fine.

Also the launcher adds the old cli arguments back to the options when restarting it after editing them manually. It ends up looking like this:

![image](https://user-images.githubusercontent.com/36563538/111328945-fe8b5200-866e-11eb-87f9-3e6e13bcfb54.png)

OS is Ubuntu 20.04
Java version is 11.0.10 openjdk using openjfx

EDIT: just removing the `\` does fix the problem too and I think that would be the correct fix for this issue

**Comment by jackjt8** [comment]
Double quotes are required for paths with spaces at least on Windows. The question is more about why there is an additional backwards slash preceding the double quotes.

**Comment by zocker-160** [comment]
ah yes I can confirm that is correct, the quotation marks are not the problem it is the backslash, just removing it, does fix the problem too

**Comment by zocker-160** [comment]
I think this line here is where it happens:
https://github.com/chunky-dev/chunky/blob/c64b83f16b86383d8028589ba6b1063a8486d5d1/launcher/src/se/llbit/chunky/launcher/JavaFxLocator.java#L65

**Comment by leMaik** [comment]
@jackjt8 Looks like the quotes were added by past you: https://github.com/chunky-dev/chunky/pull/785/files#diff-ca57cb0ae17d79c5438dbf44bef68f783feaec03e7335a856b4ca07731bff93aR65

Was there a specific reason?

@zocker-160 This looks like a great opportunity for a first PR, if you want to fix this. :upside_down_face:

**Comment by jackjt8** [comment]
Check line 64. Without that many escapes we loose the double quotes due to how the launcher gets launched again. The number of escapes is required on windows. I'm not sure why on Linux we get a `\`.

**Comment by leMaik** [comment]
`\\` explicitly adds a `\`, regardless of the platform. We could (lazy approach) check if the path starts with `/` and not add the backslash then.

**Comment by jackjt8** [comment]
Yes. The first \" escapes the first passing of ". The two additional \\ become \. The second time this line is used it is then the correct \" to become ".

Again, not sure why this would break. Would need to print the option at each step to see how it's progressing.

**Comment by leMaik** [comment]
This should be fixed by https://github.com/chunky-dev/chunky/pull/873
