### ISSUE TITLE
Water waves create a grid effect

### ISSUE THREAD

**Issue by TheRealJayjayli** [chunky-dev/chunky#880]
This is the same topic I was discussing on Discord, but I thought I'd leave a GitHub issue here as well. When viewing from a distance, the waves in water generate a grid pattern, which could be solved using some sort of perlin noise (as leMaik suggested) or something more complicated.

![image](https://user-images.githubusercontent.com/52780721/113898854-254b2d00-97c4-11eb-95e4-96552f3ad040.png)

**Comment by leMaik** [comment]
Related to #628
