### ISSUE TITLE
Way to animate animated textures like fire.

### ISSUE THREAD

**Issue by ThatRedox** [chunky-dev/chunky#889]
Fire has an animated texture ~which is currently set by the block position~. For animations, it would be nice to have some value to change that will increment the frame in animated textures.

Correction: Fire appears to always use animation frame 0

**Comment by leMaik** [comment]
I'd suggest adding a _time_ option. Animated textures can have different speeds, interpolation and lengths and by having a _time_ to render at we could take all that into account, one day we could even add water animation based on that.

**Comment by leMaik** [comment]
This would make #137 obsolete.

**Comment by leMaik** [comment]
I'll close this in favor of #1269
