### ISSUE TITLE
[water] Extreme Refraction Angles -> Black

### ISSUE THREAD

**Issue by IceSelkie** [chunky-dev/chunky#891]
When refracting the rays through the surface of water, if the angle is extreme enough the ray seems to get lost. If water opacity is above 0, it will give the color of "water" there, and at 0 it will be pure black.

Close to the surface of water:
![water blackness](https://user-images.githubusercontent.com/4878558/114609913-2eb91700-9c54-11eb-8ee2-a8ad90c5d390.png)

Zoomed in to one of the areas (towards the top left; decreased FoV):
![water blackness_2](https://user-images.githubusercontent.com/4878558/114609948-3b3d6f80-9c54-11eb-933a-e4fb273406a1.png)

One one-hundred-thousanth of a block from the edge of a glass pane:
![glasspane no black](https://user-images.githubusercontent.com/4878558/114610931-4fce3780-9c55-11eb-9662-97ccc1ffb82f.png)

**Comment by leMaik** [comment]
Water: Maybe the ray intersects with the water surface twice (because it's close to parallel to the water surface) but Chunky assumes that it has left the water at that point. Not sure, just an assumption.
