### ISSUE TITLE
Add button for Load entities

### ISSUE THREAD

**Issue by TheRealJayjayli** [chunky-dev/chunky#896]
It would be nice to see a check box for `Load entities`, similar to the one currently used for `Load players`, allowing you to switch entities off during loading.

**Comment by ShirleyNekoDev** [comment]
I'll keep this in mind once I'm working on #808 👍

**Comment by Stenodyon** [comment]
Should that prevent loading players as well?

**Comment by TheRealJayjayli** [comment]
Possibly not, so you can load players only without any other entities (so you can tick both checkboxes for no entities at all)
