### ISSUE TITLE
Broken textures(kind of?)

### ISSUE THREAD

**Issue by enpyera** [chunky-dev/chunky#907]
![world1-0](https://user-images.githubusercontent.com/37874602/115709903-6a519080-a37a-11eb-9e1b-fc13d962a35d.png)
Tried opening my survival world and for some reason i only see stuff like this.

**Comment by leMaik** [comment]
Which version of chunky are you using?

**Comment by ProNoob135** [comment]
Load the minecraft .jar as a resourcepack (it's in .minecraft\versions by default).
Also looks like you may need to restart chunky and reload the world in this case?

**Comment by enpyera** [comment]
> Which version of chunky are you using? Update to 2.3.0, that should fix it.

Yeah updating fixed it, so thanks! 
I thought i'd updated chunky, but for some reason, it refused to update or something.

But yeah, fixed it
