### ISSUE TITLE
Inaccurate Y max Calculation when Y min>0

### ISSUE THREAD

**Issue by Lohfrum-Faleign** [chunky-dev/chunky#908]
Was trying to display single layers of chunks so that I can make a schematic of a 1 chunk house I built.
I set the Y min to 73 to cut off everything below the bottom layer of the house, then I set the Y max to 74 and hit reload chunks. Instantly the layer of blocks gets teleported 53 blocks down to y=20. However if I keep Y Min at 0 and just adjust the Y Max alone, it makes the layer cuts accurately.

Y Min = 73, Y Max = 256
![image](https://user-images.githubusercontent.com/49575771/115795995-fd042680-a39e-11eb-8f1c-bdfccf293b74.png)
Y Min =73, Y Max = 74
![image](https://user-images.githubusercontent.com/49575771/115796028-0f7e6000-a39f-11eb-9ad4-9b358dfe5fdd.png)
As shown in this image, the Polished Diorite that was originally at y= 73.5 Is now at y=20.5
![image](https://user-images.githubusercontent.com/49575771/115796242-8582c700-a39f-11eb-9400-a52a1f8786a6.png)

But if you leave Y Min at 0, Adjusting the Y Max works as normal.
Here y min=0, y max=85
![image](https://user-images.githubusercontent.com/49575771/115796215-73088d80-a39f-11eb-8958-6416c2c56976.png)

**Comment by leMaik** [comment]
Related: 
![image](https://user-images.githubusercontent.com/5544859/116795120-e498b800-aad2-11eb-97b3-13bc808216fd.png)
