### ISSUE TITLE
Bottom of lava has no face

### ISSUE THREAD

**Issue by NotStirred** [chunky-dev/chunky#921]
![image](https://user-images.githubusercontent.com/16853282/116893601-12901080-ac29-11eb-95eb-257280e2f354.png)

This has been a bug for a *very* long time

**Comment by leMaik** [comment]
Does water have a bottom face?

**Comment by NotStirred** [comment]
yes

**Comment by leMaik** [comment]
![image](https://user-images.githubusercontent.com/5544859/120112162-fa060e00-c174-11eb-82e4-8e7734278640.png)
