### ISSUE TITLE
Water world broken when camera is outside of octree

### ISSUE THREAD

**Issue by aTom3333** [chunky-dev/chunky#934]
Water is completely broken when the camera is outside of the octree.
Scene without water world on:
![image](https://user-images.githubusercontent.com/23342398/118025237-e29ae880-b35f-11eb-9f8b-7d2388b58b4f.png)

Preview with water world on:
![image](https://user-images.githubusercontent.com/23342398/118025299-f9d9d600-b35f-11eb-9c1a-265b67ae8e8a.png)

Render with water world:
![image](https://user-images.githubusercontent.com/23342398/118025392-1413b400-b360-11eb-9a33-75489bc976db.png)

For reference, water world is not broken (beside the gap) when the camera is bit to the side, inside the octree:
![image](https://user-images.githubusercontent.com/23342398/118025456-2f7ebf00-b360-11eb-8284-72003e90effe.png)

**Comment by leMaik** [comment]
Can't reproduce this :thinking: 
![image](https://user-images.githubusercontent.com/5544859/118041504-2cd99500-b373-11eb-9ed1-6b22f9d87378.png)

**Comment by aTom3333** [comment]
You are maybe not outside of the octree, if your yMin-yMax is 0 - 256, the octree will have a size of 256\*256\*256 and the loaded chunks will be in a corner of that (the worner toward negative x and negative z), so if you go outside of your loaded chunks in the positive x/z direction, you are probably still inside the octree (mainly supposition for now, I haven't look in detail yet)
