### ISSUE TITLE
Parallel Projection front plane clipping

### ISSUE THREAD

**Issue by ShirleyNekoDev** [chunky-dev/chunky#942]
When using projection mode "Parallel", depending on camera rotation and FoV, parts of the scene near the camera get clipped resulting in black spots in the final render or an unidentifiable mess in the preview renderer.

Example render where mountains get clipped:
![image](https://user-images.githubusercontent.com/16897056/118354113-cbc7e200-b569-11eb-9ed1-7b697234802a.png)
Same scene in preview mode:
![image](https://user-images.githubusercontent.com/16897056/118354182-16e1f500-b56a-11eb-8f0d-c1981ac09bc3.png)

**Comment by leMaik** [comment]
Solution: Move the camera up. I don't see how we could fix this.

**Comment by aTom3333** [comment]
I see how, we would need to make the ray start "behind" the camera, far enough back that its origin is outside the octree. This should be simple enough, I'll try doing that later.

**Comment by ShirleyNekoDev** [comment]
Hacky fix: Could there be a way to automatically detect which height would be required to not clip and move it up to this height and find a matching lens shift to move the scene down to the original view?
