### ISSUE TITLE
(Preview) Renderer freezes on "New scene from selection" with empty selection

### ISSUE THREAD

**Issue by ShirleyNekoDev** [chunky-dev/chunky#945]
Tested in Chunky 2.3.0, 2.4.0-snapshot, master

Camera defaults orientation points down (-90 0 0) which results in an infinite loop in enterBlock here:
https://github.com/chunky-dev/chunky/blob/e15ee28fabf3cade8e477659f1dc39f3c3382b9b/chunky/src/java/se/llbit/math/Octree.java#L528-L643

Variables at the end of the loop:
```
x=0, y=0, z=0, depth=1,
lx=0, ly=0, lz=0,
t=NaN, distance=+Inf, invDx=+Inf
```

The while(true) loop never ends because no block can be found that can be entered, but at the same time we never went outside of the octree (lx, ly, lz = 0 because we shift 0).

**Comment by leMaik** [comment]
I'd say this is a UI bug. How about this?

![image](https://user-images.githubusercontent.com/5544859/118369792-0f8c0d00-b5a5-11eb-841e-e203d588aa8f.png)

**Comment by ShirleyNekoDev** [comment]
It is possible to create an empty scene when switching directly to render preview without selecting chunks in the map.
I use this for testing custom entities for plugins ;)
