### ISSUE TITLE
Ask users to save before quitting Chunky

### ISSUE THREAD

**Issue by TheRealJayjayli** [chunky-dev/chunky#951]
It may be useful to ask the user if they want to save their scene before closing Chunky, in case the scene wasn't saved previously.

**Comment by leMaik** [comment]
As mentioned in in #997 it would be good to also warn about loosing render progress.

**Comment by TheRealJayjayli** [comment]
Apologies, I saw the duplicate ticket was closed and accidentally thought that the feature was already implemented.

**Comment by ShirleyNekoDev** [comment]
Requirements:
- [ ] track the "dirty state" of the scene - are there unsaved changes?
- [ ] if yes, let the user confirm closing chunky

Additional features:
- [ ] show * in the title to indicate unsaved changes
- [ ] unsaved changes should also prompt the user before loading another scene

**Comment by ShirleyNekoDev** [comment]
Might be interesting to also investigate `Desktop::disableSuddenTermination()` for this
