### ISSUE TITLE
Warn the user that closing Chunky will lose render progress

### ISSUE THREAD

**Issue by ImSyphia** [chunky-dev/chunky#997]
When the user currently closes Chunky, there is no indication to the user that an ongoing render must be re-started and can not be continued from its current state. Adding a small dialogue window when closing Chunky with a non-complete render that mentions this would help prevent confusion to the user as to why the render restarts when loading Chunky again.

**Comment by MadDog443** [comment]
Yeah, Chunky not autosaving on exit or warning you before closing a unsaved project is not fun. It would be a nice feature.

**Comment by leMaik** [comment]
Turns out this is a duplicate of the even older #951
